// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatToNation.proto

#ifndef PROTOBUF_ChatToNation_2eproto__INCLUDED
#define PROTOBUF_ChatToNation_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ChatToNation_2eproto();
void protobuf_AssignDesc_ChatToNation_2eproto();
void protobuf_ShutdownFile_ChatToNation_2eproto();

class ChatToNation;

enum ChatToNation_traits {
  ChatToNation_traits_value = 3008
};
bool ChatToNation_traits_IsValid(int value);
const ChatToNation_traits ChatToNation_traits_traits_MIN = ChatToNation_traits_value;
const ChatToNation_traits ChatToNation_traits_traits_MAX = ChatToNation_traits_value;
const int ChatToNation_traits_traits_ARRAYSIZE = ChatToNation_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatToNation_traits_descriptor();
inline const ::std::string& ChatToNation_traits_Name(ChatToNation_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatToNation_traits_descriptor(), value);
}
inline bool ChatToNation_traits_Parse(
    const ::std::string& name, ChatToNation_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatToNation_traits>(
    ChatToNation_traits_descriptor(), name, value);
}
// ===================================================================

class ChatToNation : public ::google::protobuf::Message {
 public:
  ChatToNation();
  virtual ~ChatToNation();
  
  ChatToNation(const ChatToNation& from);
  
  inline ChatToNation& operator=(const ChatToNation& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatToNation& default_instance();
  
  void Swap(ChatToNation* other);
  
  // implements Message ----------------------------------------------
  
  ChatToNation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatToNation& from);
  void MergeFrom(const ChatToNation& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ChatToNation_traits traits;
  static const traits value = ChatToNation_traits_value;
  static inline bool traits_IsValid(int value) {
    return ChatToNation_traits_IsValid(value);
  }
  static const traits traits_MIN =
    ChatToNation_traits_traits_MIN;
  static const traits traits_MAX =
    ChatToNation_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    ChatToNation_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return ChatToNation_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return ChatToNation_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return ChatToNation_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 from_player = 1;
  inline bool has_from_player() const;
  inline void clear_from_player();
  static const int kFromPlayerFieldNumber = 1;
  inline ::google::protobuf::int32 from_player() const;
  inline void set_from_player(::google::protobuf::int32 value);
  
  // required bytes infomation = 2;
  inline bool has_infomation() const;
  inline void clear_infomation();
  static const int kInfomationFieldNumber = 2;
  inline const ::std::string& infomation() const;
  inline void set_infomation(const ::std::string& value);
  inline void set_infomation(const char* value);
  inline void set_infomation(const void* value, size_t size);
  inline ::std::string* mutable_infomation();
  inline ::std::string* release_infomation();
  
  // optional int32 nation = 3;
  inline bool has_nation() const;
  inline void clear_nation();
  static const int kNationFieldNumber = 3;
  inline ::google::protobuf::int32 nation() const;
  inline void set_nation(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.ChatToNation)
 private:
  inline void set_has_from_player();
  inline void clear_has_from_player();
  inline void set_has_infomation();
  inline void clear_has_infomation();
  inline void set_has_nation();
  inline void clear_has_nation();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* infomation_;
  ::google::protobuf::int32 from_player_;
  ::google::protobuf::int32 nation_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_ChatToNation_2eproto();
  friend void protobuf_AssignDesc_ChatToNation_2eproto();
  friend void protobuf_ShutdownFile_ChatToNation_2eproto();
  
  void InitAsDefaultInstance();
  static ChatToNation* default_instance_;
};
// ===================================================================


// ===================================================================

// ChatToNation

// required int32 from_player = 1;
inline bool ChatToNation::has_from_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatToNation::set_has_from_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatToNation::clear_has_from_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatToNation::clear_from_player() {
  from_player_ = 0;
  clear_has_from_player();
}
inline ::google::protobuf::int32 ChatToNation::from_player() const {
  return from_player_;
}
inline void ChatToNation::set_from_player(::google::protobuf::int32 value) {
  set_has_from_player();
  from_player_ = value;
}

// required bytes infomation = 2;
inline bool ChatToNation::has_infomation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatToNation::set_has_infomation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatToNation::clear_has_infomation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatToNation::clear_infomation() {
  if (infomation_ != &::google::protobuf::internal::kEmptyString) {
    infomation_->clear();
  }
  clear_has_infomation();
}
inline const ::std::string& ChatToNation::infomation() const {
  return *infomation_;
}
inline void ChatToNation::set_infomation(const ::std::string& value) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(value);
}
inline void ChatToNation::set_infomation(const char* value) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(value);
}
inline void ChatToNation::set_infomation(const void* value, size_t size) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatToNation::mutable_infomation() {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  return infomation_;
}
inline ::std::string* ChatToNation::release_infomation() {
  clear_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = infomation_;
    infomation_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 nation = 3;
inline bool ChatToNation::has_nation() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatToNation::set_has_nation() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatToNation::clear_has_nation() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatToNation::clear_nation() {
  nation_ = 0;
  clear_has_nation();
}
inline ::google::protobuf::int32 ChatToNation::nation() const {
  return nation_;
}
inline void ChatToNation::set_nation(::google::protobuf::int32 value) {
  set_has_nation();
  nation_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::ChatToNation_traits>() {
  return ::game_connection::ChatToNation_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ChatToNation_2eproto__INCLUDED
