// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientLogicError.proto

#ifndef PROTOBUF_ClientLogicError_2eproto__INCLUDED
#define PROTOBUF_ClientLogicError_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ClientLogicError_2eproto();
void protobuf_AssignDesc_ClientLogicError_2eproto();
void protobuf_ShutdownFile_ClientLogicError_2eproto();

class ClientLogicError;

enum ClientLogicError_traits {
  ClientLogicError_traits_value = 3222
};
bool ClientLogicError_traits_IsValid(int value);
const ClientLogicError_traits ClientLogicError_traits_traits_MIN = ClientLogicError_traits_value;
const ClientLogicError_traits ClientLogicError_traits_traits_MAX = ClientLogicError_traits_value;
const int ClientLogicError_traits_traits_ARRAYSIZE = ClientLogicError_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* ClientLogicError_traits_descriptor();
inline const ::std::string& ClientLogicError_traits_Name(ClientLogicError_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    ClientLogicError_traits_descriptor(), value);
}
inline bool ClientLogicError_traits_Parse(
    const ::std::string& name, ClientLogicError_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ClientLogicError_traits>(
    ClientLogicError_traits_descriptor(), name, value);
}
// ===================================================================

class ClientLogicError : public ::google::protobuf::Message {
 public:
  ClientLogicError();
  virtual ~ClientLogicError();
  
  ClientLogicError(const ClientLogicError& from);
  
  inline ClientLogicError& operator=(const ClientLogicError& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientLogicError& default_instance();
  
  void Swap(ClientLogicError* other);
  
  // implements Message ----------------------------------------------
  
  ClientLogicError* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientLogicError& from);
  void MergeFrom(const ClientLogicError& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ClientLogicError_traits traits;
  static const traits value = ClientLogicError_traits_value;
  static inline bool traits_IsValid(int value) {
    return ClientLogicError_traits_IsValid(value);
  }
  static const traits traits_MIN =
    ClientLogicError_traits_traits_MIN;
  static const traits traits_MAX =
    ClientLogicError_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    ClientLogicError_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return ClientLogicError_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return ClientLogicError_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return ClientLogicError_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // optional int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // optional bytes error_description = 2;
  inline bool has_error_description() const;
  inline void clear_error_description();
  static const int kErrorDescriptionFieldNumber = 2;
  inline const ::std::string& error_description() const;
  inline void set_error_description(const ::std::string& value);
  inline void set_error_description(const char* value);
  inline void set_error_description(const void* value, size_t size);
  inline ::std::string* mutable_error_description();
  inline ::std::string* release_error_description();
  
  // @@protoc_insertion_point(class_scope:game_connection.ClientLogicError)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_error_description();
  inline void clear_has_error_description();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* error_description_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ClientLogicError_2eproto();
  friend void protobuf_AssignDesc_ClientLogicError_2eproto();
  friend void protobuf_ShutdownFile_ClientLogicError_2eproto();
  
  void InitAsDefaultInstance();
  static ClientLogicError* default_instance_;
};
// ===================================================================


// ===================================================================

// ClientLogicError

// optional int32 error_code = 1;
inline bool ClientLogicError::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientLogicError::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientLogicError::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientLogicError::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 ClientLogicError::error_code() const {
  return error_code_;
}
inline void ClientLogicError::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional bytes error_description = 2;
inline bool ClientLogicError::has_error_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientLogicError::set_has_error_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientLogicError::clear_has_error_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientLogicError::clear_error_description() {
  if (error_description_ != &::google::protobuf::internal::kEmptyString) {
    error_description_->clear();
  }
  clear_has_error_description();
}
inline const ::std::string& ClientLogicError::error_description() const {
  return *error_description_;
}
inline void ClientLogicError::set_error_description(const ::std::string& value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::kEmptyString) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
}
inline void ClientLogicError::set_error_description(const char* value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::kEmptyString) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
}
inline void ClientLogicError::set_error_description(const void* value, size_t size) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::kEmptyString) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClientLogicError::mutable_error_description() {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::kEmptyString) {
    error_description_ = new ::std::string;
  }
  return error_description_;
}
inline ::std::string* ClientLogicError::release_error_description() {
  clear_has_error_description();
  if (error_description_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_description_;
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::ClientLogicError_traits>() {
  return ::game_connection::ClientLogicError_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ClientLogicError_2eproto__INCLUDED
