// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNetProperty.proto

#ifndef PROTOBUF_ClientNetProperty_2eproto__INCLUDED
#define PROTOBUF_ClientNetProperty_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ClientNetProperty_2eproto();
void protobuf_AssignDesc_ClientNetProperty_2eproto();
void protobuf_ShutdownFile_ClientNetProperty_2eproto();

class ClientNetProperty;

enum ClientNetProperty_traits {
  ClientNetProperty_traits_value = 3144
};
bool ClientNetProperty_traits_IsValid(int value);
const ClientNetProperty_traits ClientNetProperty_traits_traits_MIN = ClientNetProperty_traits_value;
const ClientNetProperty_traits ClientNetProperty_traits_traits_MAX = ClientNetProperty_traits_value;
const int ClientNetProperty_traits_traits_ARRAYSIZE = ClientNetProperty_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* ClientNetProperty_traits_descriptor();
inline const ::std::string& ClientNetProperty_traits_Name(ClientNetProperty_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    ClientNetProperty_traits_descriptor(), value);
}
inline bool ClientNetProperty_traits_Parse(
    const ::std::string& name, ClientNetProperty_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ClientNetProperty_traits>(
    ClientNetProperty_traits_descriptor(), name, value);
}
// ===================================================================

class ClientNetProperty : public ::google::protobuf::Message {
 public:
  ClientNetProperty();
  virtual ~ClientNetProperty();
  
  ClientNetProperty(const ClientNetProperty& from);
  
  inline ClientNetProperty& operator=(const ClientNetProperty& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientNetProperty& default_instance();
  
  void Swap(ClientNetProperty* other);
  
  // implements Message ----------------------------------------------
  
  ClientNetProperty* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientNetProperty& from);
  void MergeFrom(const ClientNetProperty& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ClientNetProperty_traits traits;
  static const traits value = ClientNetProperty_traits_value;
  static inline bool traits_IsValid(int value) {
    return ClientNetProperty_traits_IsValid(value);
  }
  static const traits traits_MIN =
    ClientNetProperty_traits_traits_MIN;
  static const traits traits_MAX =
    ClientNetProperty_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    ClientNetProperty_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return ClientNetProperty_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return ClientNetProperty_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return ClientNetProperty_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required uint32 max_answering_time = 1;
  inline bool has_max_answering_time() const;
  inline void clear_max_answering_time();
  static const int kMaxAnsweringTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 max_answering_time() const;
  inline void set_max_answering_time(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.ClientNetProperty)
 private:
  inline void set_has_max_answering_time();
  inline void clear_has_max_answering_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 max_answering_time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ClientNetProperty_2eproto();
  friend void protobuf_AssignDesc_ClientNetProperty_2eproto();
  friend void protobuf_ShutdownFile_ClientNetProperty_2eproto();
  
  void InitAsDefaultInstance();
  static ClientNetProperty* default_instance_;
};
// ===================================================================


// ===================================================================

// ClientNetProperty

// required uint32 max_answering_time = 1;
inline bool ClientNetProperty::has_max_answering_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientNetProperty::set_has_max_answering_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientNetProperty::clear_has_max_answering_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientNetProperty::clear_max_answering_time() {
  max_answering_time_ = 0u;
  clear_has_max_answering_time();
}
inline ::google::protobuf::uint32 ClientNetProperty::max_answering_time() const {
  return max_answering_time_;
}
inline void ClientNetProperty::set_max_answering_time(::google::protobuf::uint32 value) {
  set_has_max_answering_time();
  max_answering_time_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::ClientNetProperty_traits>() {
  return ::game_connection::ClientNetProperty_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ClientNetProperty_2eproto__INCLUDED
