// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCall_SaveChat.proto

#ifndef PROTOBUF_DataCall_5fSaveChat_2eproto__INCLUDED
#define PROTOBUF_DataCall_5fSaveChat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DataCall_5fSaveChat_2eproto();
void protobuf_AssignDesc_DataCall_5fSaveChat_2eproto();
void protobuf_ShutdownFile_DataCall_5fSaveChat_2eproto();

class DataCall_SaveChat;

enum DataCall_SaveChat_traits {
  DataCall_SaveChat_traits_value = 3258
};
bool DataCall_SaveChat_traits_IsValid(int value);
const DataCall_SaveChat_traits DataCall_SaveChat_traits_traits_MIN = DataCall_SaveChat_traits_value;
const DataCall_SaveChat_traits DataCall_SaveChat_traits_traits_MAX = DataCall_SaveChat_traits_value;
const int DataCall_SaveChat_traits_traits_ARRAYSIZE = DataCall_SaveChat_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataCall_SaveChat_traits_descriptor();
inline const ::std::string& DataCall_SaveChat_traits_Name(DataCall_SaveChat_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataCall_SaveChat_traits_descriptor(), value);
}
inline bool DataCall_SaveChat_traits_Parse(
    const ::std::string& name, DataCall_SaveChat_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataCall_SaveChat_traits>(
    DataCall_SaveChat_traits_descriptor(), name, value);
}
// ===================================================================

class DataCall_SaveChat : public ::google::protobuf::Message {
 public:
  DataCall_SaveChat();
  virtual ~DataCall_SaveChat();
  
  DataCall_SaveChat(const DataCall_SaveChat& from);
  
  inline DataCall_SaveChat& operator=(const DataCall_SaveChat& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DataCall_SaveChat& default_instance();
  
  void Swap(DataCall_SaveChat* other);
  
  // implements Message ----------------------------------------------
  
  DataCall_SaveChat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataCall_SaveChat& from);
  void MergeFrom(const DataCall_SaveChat& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef DataCall_SaveChat_traits traits;
  static const traits value = DataCall_SaveChat_traits_value;
  static inline bool traits_IsValid(int value) {
    return DataCall_SaveChat_traits_IsValid(value);
  }
  static const traits traits_MIN =
    DataCall_SaveChat_traits_traits_MIN;
  static const traits traits_MAX =
    DataCall_SaveChat_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    DataCall_SaveChat_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return DataCall_SaveChat_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return DataCall_SaveChat_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return DataCall_SaveChat_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  
  // @@protoc_insertion_point(class_scope:game_connection.DataCall_SaveChat)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* data_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataCall_5fSaveChat_2eproto();
  friend void protobuf_AssignDesc_DataCall_5fSaveChat_2eproto();
  friend void protobuf_ShutdownFile_DataCall_5fSaveChat_2eproto();
  
  void InitAsDefaultInstance();
  static DataCall_SaveChat* default_instance_;
};
// ===================================================================


// ===================================================================

// DataCall_SaveChat

// required bytes data = 1;
inline bool DataCall_SaveChat::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataCall_SaveChat::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataCall_SaveChat::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataCall_SaveChat::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& DataCall_SaveChat::data() const {
  return *data_;
}
inline void DataCall_SaveChat::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void DataCall_SaveChat::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void DataCall_SaveChat::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataCall_SaveChat::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* DataCall_SaveChat::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::DataCall_SaveChat_traits>() {
  return ::game_connection::DataCall_SaveChat_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DataCall_5fSaveChat_2eproto__INCLUDED
