// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCall_StampCurrentPlayerNumber.proto

#ifndef PROTOBUF_DataCall_5fStampCurrentPlayerNumber_2eproto__INCLUDED
#define PROTOBUF_DataCall_5fStampCurrentPlayerNumber_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DataCall_5fStampCurrentPlayerNumber_2eproto();
void protobuf_AssignDesc_DataCall_5fStampCurrentPlayerNumber_2eproto();
void protobuf_ShutdownFile_DataCall_5fStampCurrentPlayerNumber_2eproto();

class DataCall_StampCurrentPlayerNumber;

enum DataCall_StampCurrentPlayerNumber_traits {
  DataCall_StampCurrentPlayerNumber_traits_value = 7011
};
bool DataCall_StampCurrentPlayerNumber_traits_IsValid(int value);
const DataCall_StampCurrentPlayerNumber_traits DataCall_StampCurrentPlayerNumber_traits_traits_MIN = DataCall_StampCurrentPlayerNumber_traits_value;
const DataCall_StampCurrentPlayerNumber_traits DataCall_StampCurrentPlayerNumber_traits_traits_MAX = DataCall_StampCurrentPlayerNumber_traits_value;
const int DataCall_StampCurrentPlayerNumber_traits_traits_ARRAYSIZE = DataCall_StampCurrentPlayerNumber_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataCall_StampCurrentPlayerNumber_traits_descriptor();
inline const ::std::string& DataCall_StampCurrentPlayerNumber_traits_Name(DataCall_StampCurrentPlayerNumber_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataCall_StampCurrentPlayerNumber_traits_descriptor(), value);
}
inline bool DataCall_StampCurrentPlayerNumber_traits_Parse(
    const ::std::string& name, DataCall_StampCurrentPlayerNumber_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataCall_StampCurrentPlayerNumber_traits>(
    DataCall_StampCurrentPlayerNumber_traits_descriptor(), name, value);
}
// ===================================================================

class DataCall_StampCurrentPlayerNumber : public ::google::protobuf::Message {
 public:
  DataCall_StampCurrentPlayerNumber();
  virtual ~DataCall_StampCurrentPlayerNumber();
  
  DataCall_StampCurrentPlayerNumber(const DataCall_StampCurrentPlayerNumber& from);
  
  inline DataCall_StampCurrentPlayerNumber& operator=(const DataCall_StampCurrentPlayerNumber& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DataCall_StampCurrentPlayerNumber& default_instance();
  
  void Swap(DataCall_StampCurrentPlayerNumber* other);
  
  // implements Message ----------------------------------------------
  
  DataCall_StampCurrentPlayerNumber* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataCall_StampCurrentPlayerNumber& from);
  void MergeFrom(const DataCall_StampCurrentPlayerNumber& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef DataCall_StampCurrentPlayerNumber_traits traits;
  static const traits value = DataCall_StampCurrentPlayerNumber_traits_value;
  static inline bool traits_IsValid(int value) {
    return DataCall_StampCurrentPlayerNumber_traits_IsValid(value);
  }
  static const traits traits_MIN =
    DataCall_StampCurrentPlayerNumber_traits_traits_MIN;
  static const traits traits_MAX =
    DataCall_StampCurrentPlayerNumber_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    DataCall_StampCurrentPlayerNumber_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return DataCall_StampCurrentPlayerNumber_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return DataCall_StampCurrentPlayerNumber_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return DataCall_StampCurrentPlayerNumber_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required uint32 current_player_number = 1;
  inline bool has_current_player_number() const;
  inline void clear_current_player_number();
  static const int kCurrentPlayerNumberFieldNumber = 1;
  inline ::google::protobuf::uint32 current_player_number() const;
  inline void set_current_player_number(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.DataCall_StampCurrentPlayerNumber)
 private:
  inline void set_has_current_player_number();
  inline void clear_has_current_player_number();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 current_player_number_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataCall_5fStampCurrentPlayerNumber_2eproto();
  friend void protobuf_AssignDesc_DataCall_5fStampCurrentPlayerNumber_2eproto();
  friend void protobuf_ShutdownFile_DataCall_5fStampCurrentPlayerNumber_2eproto();
  
  void InitAsDefaultInstance();
  static DataCall_StampCurrentPlayerNumber* default_instance_;
};
// ===================================================================


// ===================================================================

// DataCall_StampCurrentPlayerNumber

// required uint32 current_player_number = 1;
inline bool DataCall_StampCurrentPlayerNumber::has_current_player_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataCall_StampCurrentPlayerNumber::set_has_current_player_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataCall_StampCurrentPlayerNumber::clear_has_current_player_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataCall_StampCurrentPlayerNumber::clear_current_player_number() {
  current_player_number_ = 0u;
  clear_has_current_player_number();
}
inline ::google::protobuf::uint32 DataCall_StampCurrentPlayerNumber::current_player_number() const {
  return current_player_number_;
}
inline void DataCall_StampCurrentPlayerNumber::set_current_player_number(::google::protobuf::uint32 value) {
  set_has_current_player_number();
  current_player_number_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::DataCall_StampCurrentPlayerNumber_traits>() {
  return ::game_connection::DataCall_StampCurrentPlayerNumber_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DataCall_5fStampCurrentPlayerNumber_2eproto__INCLUDED
