// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Log_OnlineState.proto

#ifndef PROTOBUF_Log_5fOnlineState_2eproto__INCLUDED
#define PROTOBUF_Log_5fOnlineState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Log_5fOnlineState_2eproto();
void protobuf_AssignDesc_Log_5fOnlineState_2eproto();
void protobuf_ShutdownFile_Log_5fOnlineState_2eproto();

class Log_OnlineState;
class Log_OnlineState_State;

enum Log_OnlineState_traits {
  Log_OnlineState_traits_value = 12001
};
bool Log_OnlineState_traits_IsValid(int value);
const Log_OnlineState_traits Log_OnlineState_traits_traits_MIN = Log_OnlineState_traits_value;
const Log_OnlineState_traits Log_OnlineState_traits_traits_MAX = Log_OnlineState_traits_value;
const int Log_OnlineState_traits_traits_ARRAYSIZE = Log_OnlineState_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* Log_OnlineState_traits_descriptor();
inline const ::std::string& Log_OnlineState_traits_Name(Log_OnlineState_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    Log_OnlineState_traits_descriptor(), value);
}
inline bool Log_OnlineState_traits_Parse(
    const ::std::string& name, Log_OnlineState_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Log_OnlineState_traits>(
    Log_OnlineState_traits_descriptor(), name, value);
}
// ===================================================================

class Log_OnlineState_State : public ::google::protobuf::Message {
 public:
  Log_OnlineState_State();
  virtual ~Log_OnlineState_State();
  
  Log_OnlineState_State(const Log_OnlineState_State& from);
  
  inline Log_OnlineState_State& operator=(const Log_OnlineState_State& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Log_OnlineState_State& default_instance();
  
  void Swap(Log_OnlineState_State* other);
  
  // implements Message ----------------------------------------------
  
  Log_OnlineState_State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Log_OnlineState_State& from);
  void MergeFrom(const Log_OnlineState_State& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float count = 1;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 1;
  inline float count() const;
  inline void set_count(float value);
  
  // required int32 new_player = 2;
  inline bool has_new_player() const;
  inline void clear_new_player();
  static const int kNewPlayerFieldNumber = 2;
  inline ::google::protobuf::int32 new_player() const;
  inline void set_new_player(::google::protobuf::int32 value);
  
  // optional int32 min_online = 3;
  inline bool has_min_online() const;
  inline void clear_min_online();
  static const int kMinOnlineFieldNumber = 3;
  inline ::google::protobuf::int32 min_online() const;
  inline void set_min_online(::google::protobuf::int32 value);
  
  // optional int32 max_online = 4;
  inline bool has_max_online() const;
  inline void clear_max_online();
  static const int kMaxOnlineFieldNumber = 4;
  inline ::google::protobuf::int32 max_online() const;
  inline void set_max_online(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.Log_OnlineState.State)
 private:
  inline void set_has_count();
  inline void clear_has_count();
  inline void set_has_new_player();
  inline void clear_has_new_player();
  inline void set_has_min_online();
  inline void clear_has_min_online();
  inline void set_has_max_online();
  inline void clear_has_max_online();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float count_;
  ::google::protobuf::int32 new_player_;
  ::google::protobuf::int32 min_online_;
  ::google::protobuf::int32 max_online_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Log_5fOnlineState_2eproto();
  friend void protobuf_AssignDesc_Log_5fOnlineState_2eproto();
  friend void protobuf_ShutdownFile_Log_5fOnlineState_2eproto();
  
  void InitAsDefaultInstance();
  static Log_OnlineState_State* default_instance_;
};
// -------------------------------------------------------------------

class Log_OnlineState : public ::google::protobuf::Message {
 public:
  Log_OnlineState();
  virtual ~Log_OnlineState();
  
  Log_OnlineState(const Log_OnlineState& from);
  
  inline Log_OnlineState& operator=(const Log_OnlineState& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Log_OnlineState& default_instance();
  
  void Swap(Log_OnlineState* other);
  
  // implements Message ----------------------------------------------
  
  Log_OnlineState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Log_OnlineState& from);
  void MergeFrom(const Log_OnlineState& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Log_OnlineState_State State;
  
  typedef Log_OnlineState_traits traits;
  static const traits value = Log_OnlineState_traits_value;
  static inline bool traits_IsValid(int value) {
    return Log_OnlineState_traits_IsValid(value);
  }
  static const traits traits_MIN =
    Log_OnlineState_traits_traits_MIN;
  static const traits traits_MAX =
    Log_OnlineState_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    Log_OnlineState_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return Log_OnlineState_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return Log_OnlineState_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return Log_OnlineState_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 max_player_number = 1;
  inline bool has_max_player_number() const;
  inline void clear_max_player_number();
  static const int kMaxPlayerNumberFieldNumber = 1;
  inline ::google::protobuf::int32 max_player_number() const;
  inline void set_max_player_number(::google::protobuf::int32 value);
  
  // repeated .game_connection.Log_OnlineState.State new_state = 2;
  inline int new_state_size() const;
  inline void clear_new_state();
  static const int kNewStateFieldNumber = 2;
  inline const ::game_connection::Log_OnlineState_State& new_state(int index) const;
  inline ::game_connection::Log_OnlineState_State* mutable_new_state(int index);
  inline ::game_connection::Log_OnlineState_State* add_new_state();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::Log_OnlineState_State >&
      new_state() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::Log_OnlineState_State >*
      mutable_new_state();
  
  // @@protoc_insertion_point(class_scope:game_connection.Log_OnlineState)
 private:
  inline void set_has_max_player_number();
  inline void clear_has_max_player_number();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::game_connection::Log_OnlineState_State > new_state_;
  ::google::protobuf::int32 max_player_number_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_Log_5fOnlineState_2eproto();
  friend void protobuf_AssignDesc_Log_5fOnlineState_2eproto();
  friend void protobuf_ShutdownFile_Log_5fOnlineState_2eproto();
  
  void InitAsDefaultInstance();
  static Log_OnlineState* default_instance_;
};
// ===================================================================


// ===================================================================

// Log_OnlineState_State

// required float count = 1;
inline bool Log_OnlineState_State::has_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Log_OnlineState_State::set_has_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Log_OnlineState_State::clear_has_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Log_OnlineState_State::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline float Log_OnlineState_State::count() const {
  return count_;
}
inline void Log_OnlineState_State::set_count(float value) {
  set_has_count();
  count_ = value;
}

// required int32 new_player = 2;
inline bool Log_OnlineState_State::has_new_player() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Log_OnlineState_State::set_has_new_player() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Log_OnlineState_State::clear_has_new_player() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Log_OnlineState_State::clear_new_player() {
  new_player_ = 0;
  clear_has_new_player();
}
inline ::google::protobuf::int32 Log_OnlineState_State::new_player() const {
  return new_player_;
}
inline void Log_OnlineState_State::set_new_player(::google::protobuf::int32 value) {
  set_has_new_player();
  new_player_ = value;
}

// optional int32 min_online = 3;
inline bool Log_OnlineState_State::has_min_online() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Log_OnlineState_State::set_has_min_online() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Log_OnlineState_State::clear_has_min_online() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Log_OnlineState_State::clear_min_online() {
  min_online_ = 0;
  clear_has_min_online();
}
inline ::google::protobuf::int32 Log_OnlineState_State::min_online() const {
  return min_online_;
}
inline void Log_OnlineState_State::set_min_online(::google::protobuf::int32 value) {
  set_has_min_online();
  min_online_ = value;
}

// optional int32 max_online = 4;
inline bool Log_OnlineState_State::has_max_online() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Log_OnlineState_State::set_has_max_online() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Log_OnlineState_State::clear_has_max_online() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Log_OnlineState_State::clear_max_online() {
  max_online_ = 0;
  clear_has_max_online();
}
inline ::google::protobuf::int32 Log_OnlineState_State::max_online() const {
  return max_online_;
}
inline void Log_OnlineState_State::set_max_online(::google::protobuf::int32 value) {
  set_has_max_online();
  max_online_ = value;
}

// -------------------------------------------------------------------

// Log_OnlineState

// required int32 max_player_number = 1;
inline bool Log_OnlineState::has_max_player_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Log_OnlineState::set_has_max_player_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Log_OnlineState::clear_has_max_player_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Log_OnlineState::clear_max_player_number() {
  max_player_number_ = 0;
  clear_has_max_player_number();
}
inline ::google::protobuf::int32 Log_OnlineState::max_player_number() const {
  return max_player_number_;
}
inline void Log_OnlineState::set_max_player_number(::google::protobuf::int32 value) {
  set_has_max_player_number();
  max_player_number_ = value;
}

// repeated .game_connection.Log_OnlineState.State new_state = 2;
inline int Log_OnlineState::new_state_size() const {
  return new_state_.size();
}
inline void Log_OnlineState::clear_new_state() {
  new_state_.Clear();
}
inline const ::game_connection::Log_OnlineState_State& Log_OnlineState::new_state(int index) const {
  return new_state_.Get(index);
}
inline ::game_connection::Log_OnlineState_State* Log_OnlineState::mutable_new_state(int index) {
  return new_state_.Mutable(index);
}
inline ::game_connection::Log_OnlineState_State* Log_OnlineState::add_new_state() {
  return new_state_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::Log_OnlineState_State >&
Log_OnlineState::new_state() const {
  return new_state_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::Log_OnlineState_State >*
Log_OnlineState::mutable_new_state() {
  return &new_state_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Log_OnlineState_traits>() {
  return ::game_connection::Log_OnlineState_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Log_5fOnlineState_2eproto__INCLUDED
