// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Platform_ArmyGroupStarWarStart.proto

#ifndef PROTOBUF_Platform_5fArmyGroupStarWarStart_2eproto__INCLUDED
#define PROTOBUF_Platform_5fArmyGroupStarWarStart_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Platform_5fArmyGroupStarWarStart_2eproto();
void protobuf_AssignDesc_Platform_5fArmyGroupStarWarStart_2eproto();
void protobuf_ShutdownFile_Platform_5fArmyGroupStarWarStart_2eproto();

class Platform_ArmyGroupStarWarStart;

enum Platform_ArmyGroupStarWarStart_traits {
  Platform_ArmyGroupStarWarStart_traits_value = 10053
};
bool Platform_ArmyGroupStarWarStart_traits_IsValid(int value);
const Platform_ArmyGroupStarWarStart_traits Platform_ArmyGroupStarWarStart_traits_traits_MIN = Platform_ArmyGroupStarWarStart_traits_value;
const Platform_ArmyGroupStarWarStart_traits Platform_ArmyGroupStarWarStart_traits_traits_MAX = Platform_ArmyGroupStarWarStart_traits_value;
const int Platform_ArmyGroupStarWarStart_traits_traits_ARRAYSIZE = Platform_ArmyGroupStarWarStart_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* Platform_ArmyGroupStarWarStart_traits_descriptor();
inline const ::std::string& Platform_ArmyGroupStarWarStart_traits_Name(Platform_ArmyGroupStarWarStart_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    Platform_ArmyGroupStarWarStart_traits_descriptor(), value);
}
inline bool Platform_ArmyGroupStarWarStart_traits_Parse(
    const ::std::string& name, Platform_ArmyGroupStarWarStart_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Platform_ArmyGroupStarWarStart_traits>(
    Platform_ArmyGroupStarWarStart_traits_descriptor(), name, value);
}
// ===================================================================

class Platform_ArmyGroupStarWarStart : public ::google::protobuf::Message {
 public:
  Platform_ArmyGroupStarWarStart();
  virtual ~Platform_ArmyGroupStarWarStart();
  
  Platform_ArmyGroupStarWarStart(const Platform_ArmyGroupStarWarStart& from);
  
  inline Platform_ArmyGroupStarWarStart& operator=(const Platform_ArmyGroupStarWarStart& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Platform_ArmyGroupStarWarStart& default_instance();
  
  void Swap(Platform_ArmyGroupStarWarStart* other);
  
  // implements Message ----------------------------------------------
  
  Platform_ArmyGroupStarWarStart* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Platform_ArmyGroupStarWarStart& from);
  void MergeFrom(const Platform_ArmyGroupStarWarStart& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Platform_ArmyGroupStarWarStart_traits traits;
  static const traits value = Platform_ArmyGroupStarWarStart_traits_value;
  static inline bool traits_IsValid(int value) {
    return Platform_ArmyGroupStarWarStart_traits_IsValid(value);
  }
  static const traits traits_MIN =
    Platform_ArmyGroupStarWarStart_traits_traits_MIN;
  static const traits traits_MAX =
    Platform_ArmyGroupStarWarStart_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    Platform_ArmyGroupStarWarStart_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return Platform_ArmyGroupStarWarStart_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return Platform_ArmyGroupStarWarStart_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return Platform_ArmyGroupStarWarStart_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // repeated int32 star_id = 1;
  inline int star_id_size() const;
  inline void clear_star_id();
  static const int kStarIdFieldNumber = 1;
  inline ::google::protobuf::int32 star_id(int index) const;
  inline void set_star_id(int index, ::google::protobuf::int32 value);
  inline void add_star_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      star_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_star_id();
  
  // @@protoc_insertion_point(class_scope:game_connection.Platform_ArmyGroupStarWarStart)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > star_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_Platform_5fArmyGroupStarWarStart_2eproto();
  friend void protobuf_AssignDesc_Platform_5fArmyGroupStarWarStart_2eproto();
  friend void protobuf_ShutdownFile_Platform_5fArmyGroupStarWarStart_2eproto();
  
  void InitAsDefaultInstance();
  static Platform_ArmyGroupStarWarStart* default_instance_;
};
// ===================================================================


// ===================================================================

// Platform_ArmyGroupStarWarStart

// repeated int32 star_id = 1;
inline int Platform_ArmyGroupStarWarStart::star_id_size() const {
  return star_id_.size();
}
inline void Platform_ArmyGroupStarWarStart::clear_star_id() {
  star_id_.Clear();
}
inline ::google::protobuf::int32 Platform_ArmyGroupStarWarStart::star_id(int index) const {
  return star_id_.Get(index);
}
inline void Platform_ArmyGroupStarWarStart::set_star_id(int index, ::google::protobuf::int32 value) {
  star_id_.Set(index, value);
}
inline void Platform_ArmyGroupStarWarStart::add_star_id(::google::protobuf::int32 value) {
  star_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Platform_ArmyGroupStarWarStart::star_id() const {
  return star_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Platform_ArmyGroupStarWarStart::mutable_star_id() {
  return &star_id_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Platform_ArmyGroupStarWarStart_traits>() {
  return ::game_connection::Platform_ArmyGroupStarWarStart_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Platform_5fArmyGroupStarWarStart_2eproto__INCLUDED
