// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerDealFriendApplicantFailed.proto

#ifndef PROTOBUF_PlayerDealFriendApplicantFailed_2eproto__INCLUDED
#define PROTOBUF_PlayerDealFriendApplicantFailed_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PlayerDealFriendApplicantFailed_2eproto();
void protobuf_AssignDesc_PlayerDealFriendApplicantFailed_2eproto();
void protobuf_ShutdownFile_PlayerDealFriendApplicantFailed_2eproto();

class PlayerDealFriendApplicantFailed;

enum PlayerDealFriendApplicantFailed_traits {
  PlayerDealFriendApplicantFailed_traits_value = 3572
};
bool PlayerDealFriendApplicantFailed_traits_IsValid(int value);
const PlayerDealFriendApplicantFailed_traits PlayerDealFriendApplicantFailed_traits_traits_MIN = PlayerDealFriendApplicantFailed_traits_value;
const PlayerDealFriendApplicantFailed_traits PlayerDealFriendApplicantFailed_traits_traits_MAX = PlayerDealFriendApplicantFailed_traits_value;
const int PlayerDealFriendApplicantFailed_traits_traits_ARRAYSIZE = PlayerDealFriendApplicantFailed_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* PlayerDealFriendApplicantFailed_traits_descriptor();
inline const ::std::string& PlayerDealFriendApplicantFailed_traits_Name(PlayerDealFriendApplicantFailed_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    PlayerDealFriendApplicantFailed_traits_descriptor(), value);
}
inline bool PlayerDealFriendApplicantFailed_traits_Parse(
    const ::std::string& name, PlayerDealFriendApplicantFailed_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PlayerDealFriendApplicantFailed_traits>(
    PlayerDealFriendApplicantFailed_traits_descriptor(), name, value);
}
// ===================================================================

class PlayerDealFriendApplicantFailed : public ::google::protobuf::Message {
 public:
  PlayerDealFriendApplicantFailed();
  virtual ~PlayerDealFriendApplicantFailed();
  
  PlayerDealFriendApplicantFailed(const PlayerDealFriendApplicantFailed& from);
  
  inline PlayerDealFriendApplicantFailed& operator=(const PlayerDealFriendApplicantFailed& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerDealFriendApplicantFailed& default_instance();
  
  void Swap(PlayerDealFriendApplicantFailed* other);
  
  // implements Message ----------------------------------------------
  
  PlayerDealFriendApplicantFailed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerDealFriendApplicantFailed& from);
  void MergeFrom(const PlayerDealFriendApplicantFailed& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef PlayerDealFriendApplicantFailed_traits traits;
  static const traits value = PlayerDealFriendApplicantFailed_traits_value;
  static inline bool traits_IsValid(int value) {
    return PlayerDealFriendApplicantFailed_traits_IsValid(value);
  }
  static const traits traits_MIN =
    PlayerDealFriendApplicantFailed_traits_traits_MIN;
  static const traits traits_MAX =
    PlayerDealFriendApplicantFailed_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    PlayerDealFriendApplicantFailed_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return PlayerDealFriendApplicantFailed_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return PlayerDealFriendApplicantFailed_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return PlayerDealFriendApplicantFailed_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 applicant = 1;
  inline bool has_applicant() const;
  inline void clear_applicant();
  static const int kApplicantFieldNumber = 1;
  inline ::google::protobuf::int32 applicant() const;
  inline void set_applicant(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.PlayerDealFriendApplicantFailed)
 private:
  inline void set_has_applicant();
  inline void clear_has_applicant();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 applicant_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_PlayerDealFriendApplicantFailed_2eproto();
  friend void protobuf_AssignDesc_PlayerDealFriendApplicantFailed_2eproto();
  friend void protobuf_ShutdownFile_PlayerDealFriendApplicantFailed_2eproto();
  
  void InitAsDefaultInstance();
  static PlayerDealFriendApplicantFailed* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerDealFriendApplicantFailed

// required int32 applicant = 1;
inline bool PlayerDealFriendApplicantFailed::has_applicant() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerDealFriendApplicantFailed::set_has_applicant() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerDealFriendApplicantFailed::clear_has_applicant() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerDealFriendApplicantFailed::clear_applicant() {
  applicant_ = 0;
  clear_has_applicant();
}
inline ::google::protobuf::int32 PlayerDealFriendApplicantFailed::applicant() const {
  return applicant_;
}
inline void PlayerDealFriendApplicantFailed::set_applicant(::google::protobuf::int32 value) {
  set_has_applicant();
  applicant_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::PlayerDealFriendApplicantFailed_traits>() {
  return ::game_connection::PlayerDealFriendApplicantFailed_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PlayerDealFriendApplicantFailed_2eproto__INCLUDED
