// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryPlayerOnlineState.proto

#ifndef PROTOBUF_QueryPlayerOnlineState_2eproto__INCLUDED
#define PROTOBUF_QueryPlayerOnlineState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_QueryPlayerOnlineState_2eproto();
void protobuf_AssignDesc_QueryPlayerOnlineState_2eproto();
void protobuf_ShutdownFile_QueryPlayerOnlineState_2eproto();

class QueryPlayerOnlineState;

enum QueryPlayerOnlineState_traits {
  QueryPlayerOnlineState_traits_value = 3257
};
bool QueryPlayerOnlineState_traits_IsValid(int value);
const QueryPlayerOnlineState_traits QueryPlayerOnlineState_traits_traits_MIN = QueryPlayerOnlineState_traits_value;
const QueryPlayerOnlineState_traits QueryPlayerOnlineState_traits_traits_MAX = QueryPlayerOnlineState_traits_value;
const int QueryPlayerOnlineState_traits_traits_ARRAYSIZE = QueryPlayerOnlineState_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryPlayerOnlineState_traits_descriptor();
inline const ::std::string& QueryPlayerOnlineState_traits_Name(QueryPlayerOnlineState_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryPlayerOnlineState_traits_descriptor(), value);
}
inline bool QueryPlayerOnlineState_traits_Parse(
    const ::std::string& name, QueryPlayerOnlineState_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryPlayerOnlineState_traits>(
    QueryPlayerOnlineState_traits_descriptor(), name, value);
}
enum QueryPlayerOnlineState_Limit {
  QueryPlayerOnlineState_Limit_MaxQuerySize = 20
};
bool QueryPlayerOnlineState_Limit_IsValid(int value);
const QueryPlayerOnlineState_Limit QueryPlayerOnlineState_Limit_Limit_MIN = QueryPlayerOnlineState_Limit_MaxQuerySize;
const QueryPlayerOnlineState_Limit QueryPlayerOnlineState_Limit_Limit_MAX = QueryPlayerOnlineState_Limit_MaxQuerySize;
const int QueryPlayerOnlineState_Limit_Limit_ARRAYSIZE = QueryPlayerOnlineState_Limit_Limit_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryPlayerOnlineState_Limit_descriptor();
inline const ::std::string& QueryPlayerOnlineState_Limit_Name(QueryPlayerOnlineState_Limit value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryPlayerOnlineState_Limit_descriptor(), value);
}
inline bool QueryPlayerOnlineState_Limit_Parse(
    const ::std::string& name, QueryPlayerOnlineState_Limit* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryPlayerOnlineState_Limit>(
    QueryPlayerOnlineState_Limit_descriptor(), name, value);
}
// ===================================================================

class QueryPlayerOnlineState : public ::google::protobuf::Message {
 public:
  QueryPlayerOnlineState();
  virtual ~QueryPlayerOnlineState();
  
  QueryPlayerOnlineState(const QueryPlayerOnlineState& from);
  
  inline QueryPlayerOnlineState& operator=(const QueryPlayerOnlineState& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryPlayerOnlineState& default_instance();
  
  void Swap(QueryPlayerOnlineState* other);
  
  // implements Message ----------------------------------------------
  
  QueryPlayerOnlineState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QueryPlayerOnlineState& from);
  void MergeFrom(const QueryPlayerOnlineState& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef QueryPlayerOnlineState_traits traits;
  static const traits value = QueryPlayerOnlineState_traits_value;
  static inline bool traits_IsValid(int value) {
    return QueryPlayerOnlineState_traits_IsValid(value);
  }
  static const traits traits_MIN =
    QueryPlayerOnlineState_traits_traits_MIN;
  static const traits traits_MAX =
    QueryPlayerOnlineState_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    QueryPlayerOnlineState_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return QueryPlayerOnlineState_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return QueryPlayerOnlineState_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return QueryPlayerOnlineState_traits_Parse(name, value);
  }
  
  typedef QueryPlayerOnlineState_Limit Limit;
  static const Limit MaxQuerySize = QueryPlayerOnlineState_Limit_MaxQuerySize;
  static inline bool Limit_IsValid(int value) {
    return QueryPlayerOnlineState_Limit_IsValid(value);
  }
  static const Limit Limit_MIN =
    QueryPlayerOnlineState_Limit_Limit_MIN;
  static const Limit Limit_MAX =
    QueryPlayerOnlineState_Limit_Limit_MAX;
  static const int Limit_ARRAYSIZE =
    QueryPlayerOnlineState_Limit_Limit_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Limit_descriptor() {
    return QueryPlayerOnlineState_Limit_descriptor();
  }
  static inline const ::std::string& Limit_Name(Limit value) {
    return QueryPlayerOnlineState_Limit_Name(value);
  }
  static inline bool Limit_Parse(const ::std::string& name,
      Limit* value) {
    return QueryPlayerOnlineState_Limit_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // repeated int32 player_id = 1;
  inline int player_id_size() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id(int index) const;
  inline void set_player_id(int index, ::google::protobuf::int32 value);
  inline void add_player_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      player_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_player_id();
  
  // optional int32 session_id = 2;
  inline bool has_session_id() const;
  inline void clear_session_id();
  static const int kSessionIdFieldNumber = 2;
  inline ::google::protobuf::int32 session_id() const;
  inline void set_session_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.QueryPlayerOnlineState)
 private:
  inline void set_has_session_id();
  inline void clear_has_session_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > player_id_;
  ::google::protobuf::int32 session_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_QueryPlayerOnlineState_2eproto();
  friend void protobuf_AssignDesc_QueryPlayerOnlineState_2eproto();
  friend void protobuf_ShutdownFile_QueryPlayerOnlineState_2eproto();
  
  void InitAsDefaultInstance();
  static QueryPlayerOnlineState* default_instance_;
};
// ===================================================================


// ===================================================================

// QueryPlayerOnlineState

// repeated int32 player_id = 1;
inline int QueryPlayerOnlineState::player_id_size() const {
  return player_id_.size();
}
inline void QueryPlayerOnlineState::clear_player_id() {
  player_id_.Clear();
}
inline ::google::protobuf::int32 QueryPlayerOnlineState::player_id(int index) const {
  return player_id_.Get(index);
}
inline void QueryPlayerOnlineState::set_player_id(int index, ::google::protobuf::int32 value) {
  player_id_.Set(index, value);
}
inline void QueryPlayerOnlineState::add_player_id(::google::protobuf::int32 value) {
  player_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
QueryPlayerOnlineState::player_id() const {
  return player_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
QueryPlayerOnlineState::mutable_player_id() {
  return &player_id_;
}

// optional int32 session_id = 2;
inline bool QueryPlayerOnlineState::has_session_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QueryPlayerOnlineState::set_has_session_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QueryPlayerOnlineState::clear_has_session_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QueryPlayerOnlineState::clear_session_id() {
  session_id_ = 0;
  clear_has_session_id();
}
inline ::google::protobuf::int32 QueryPlayerOnlineState::session_id() const {
  return session_id_;
}
inline void QueryPlayerOnlineState::set_session_id(::google::protobuf::int32 value) {
  set_has_session_id();
  session_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::QueryPlayerOnlineState_traits>() {
  return ::game_connection::QueryPlayerOnlineState_traits_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::QueryPlayerOnlineState_Limit>() {
  return ::game_connection::QueryPlayerOnlineState_Limit_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_QueryPlayerOnlineState_2eproto__INCLUDED
