// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radio_ArmyGroupDispatch.proto

#ifndef PROTOBUF_Radio_5fArmyGroupDispatch_2eproto__INCLUDED
#define PROTOBUF_Radio_5fArmyGroupDispatch_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Radio_5fArmyGroupDispatch_2eproto();
void protobuf_AssignDesc_Radio_5fArmyGroupDispatch_2eproto();
void protobuf_ShutdownFile_Radio_5fArmyGroupDispatch_2eproto();

class Radio_ArmyGroupDispatch;

enum Radio_ArmyGroupDispatch_traits {
  Radio_ArmyGroupDispatch_traits_value = 3399
};
bool Radio_ArmyGroupDispatch_traits_IsValid(int value);
const Radio_ArmyGroupDispatch_traits Radio_ArmyGroupDispatch_traits_traits_MIN = Radio_ArmyGroupDispatch_traits_value;
const Radio_ArmyGroupDispatch_traits Radio_ArmyGroupDispatch_traits_traits_MAX = Radio_ArmyGroupDispatch_traits_value;
const int Radio_ArmyGroupDispatch_traits_traits_ARRAYSIZE = Radio_ArmyGroupDispatch_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* Radio_ArmyGroupDispatch_traits_descriptor();
inline const ::std::string& Radio_ArmyGroupDispatch_traits_Name(Radio_ArmyGroupDispatch_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    Radio_ArmyGroupDispatch_traits_descriptor(), value);
}
inline bool Radio_ArmyGroupDispatch_traits_Parse(
    const ::std::string& name, Radio_ArmyGroupDispatch_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Radio_ArmyGroupDispatch_traits>(
    Radio_ArmyGroupDispatch_traits_descriptor(), name, value);
}
// ===================================================================

class Radio_ArmyGroupDispatch : public ::google::protobuf::Message {
 public:
  Radio_ArmyGroupDispatch();
  virtual ~Radio_ArmyGroupDispatch();
  
  Radio_ArmyGroupDispatch(const Radio_ArmyGroupDispatch& from);
  
  inline Radio_ArmyGroupDispatch& operator=(const Radio_ArmyGroupDispatch& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Radio_ArmyGroupDispatch& default_instance();
  
  void Swap(Radio_ArmyGroupDispatch* other);
  
  // implements Message ----------------------------------------------
  
  Radio_ArmyGroupDispatch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Radio_ArmyGroupDispatch& from);
  void MergeFrom(const Radio_ArmyGroupDispatch& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Radio_ArmyGroupDispatch_traits traits;
  static const traits value = Radio_ArmyGroupDispatch_traits_value;
  static inline bool traits_IsValid(int value) {
    return Radio_ArmyGroupDispatch_traits_IsValid(value);
  }
  static const traits traits_MIN =
    Radio_ArmyGroupDispatch_traits_traits_MIN;
  static const traits traits_MAX =
    Radio_ArmyGroupDispatch_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    Radio_ArmyGroupDispatch_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return Radio_ArmyGroupDispatch_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return Radio_ArmyGroupDispatch_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return Radio_ArmyGroupDispatch_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required bytes action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline const ::std::string& action() const;
  inline void set_action(const ::std::string& value);
  inline void set_action(const char* value);
  inline void set_action(const void* value, size_t size);
  inline ::std::string* mutable_action();
  inline ::std::string* release_action();
  
  // @@protoc_insertion_point(class_scope:game_connection.Radio_ArmyGroupDispatch)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* action_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_Radio_5fArmyGroupDispatch_2eproto();
  friend void protobuf_AssignDesc_Radio_5fArmyGroupDispatch_2eproto();
  friend void protobuf_ShutdownFile_Radio_5fArmyGroupDispatch_2eproto();
  
  void InitAsDefaultInstance();
  static Radio_ArmyGroupDispatch* default_instance_;
};
// ===================================================================


// ===================================================================

// Radio_ArmyGroupDispatch

// required bytes action = 1;
inline bool Radio_ArmyGroupDispatch::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Radio_ArmyGroupDispatch::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Radio_ArmyGroupDispatch::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Radio_ArmyGroupDispatch::clear_action() {
  if (action_ != &::google::protobuf::internal::kEmptyString) {
    action_->clear();
  }
  clear_has_action();
}
inline const ::std::string& Radio_ArmyGroupDispatch::action() const {
  return *action_;
}
inline void Radio_ArmyGroupDispatch::set_action(const ::std::string& value) {
  set_has_action();
  if (action_ == &::google::protobuf::internal::kEmptyString) {
    action_ = new ::std::string;
  }
  action_->assign(value);
}
inline void Radio_ArmyGroupDispatch::set_action(const char* value) {
  set_has_action();
  if (action_ == &::google::protobuf::internal::kEmptyString) {
    action_ = new ::std::string;
  }
  action_->assign(value);
}
inline void Radio_ArmyGroupDispatch::set_action(const void* value, size_t size) {
  set_has_action();
  if (action_ == &::google::protobuf::internal::kEmptyString) {
    action_ = new ::std::string;
  }
  action_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Radio_ArmyGroupDispatch::mutable_action() {
  set_has_action();
  if (action_ == &::google::protobuf::internal::kEmptyString) {
    action_ = new ::std::string;
  }
  return action_;
}
inline ::std::string* Radio_ArmyGroupDispatch::release_action() {
  clear_has_action();
  if (action_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = action_;
    action_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Radio_ArmyGroupDispatch_traits>() {
  return ::game_connection::Radio_ArmyGroupDispatch_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Radio_5fArmyGroupDispatch_2eproto__INCLUDED
