// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radio_ArmyGroupGiveUpStar.proto

#ifndef PROTOBUF_Radio_5fArmyGroupGiveUpStar_2eproto__INCLUDED
#define PROTOBUF_Radio_5fArmyGroupGiveUpStar_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Radio_5fArmyGroupGiveUpStar_2eproto();
void protobuf_AssignDesc_Radio_5fArmyGroupGiveUpStar_2eproto();
void protobuf_ShutdownFile_Radio_5fArmyGroupGiveUpStar_2eproto();

class Radio_ArmyGroupGiveUpStar;

enum Radio_ArmyGroupGiveUpStar_traits {
  Radio_ArmyGroupGiveUpStar_traits_value = 3375
};
bool Radio_ArmyGroupGiveUpStar_traits_IsValid(int value);
const Radio_ArmyGroupGiveUpStar_traits Radio_ArmyGroupGiveUpStar_traits_traits_MIN = Radio_ArmyGroupGiveUpStar_traits_value;
const Radio_ArmyGroupGiveUpStar_traits Radio_ArmyGroupGiveUpStar_traits_traits_MAX = Radio_ArmyGroupGiveUpStar_traits_value;
const int Radio_ArmyGroupGiveUpStar_traits_traits_ARRAYSIZE = Radio_ArmyGroupGiveUpStar_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* Radio_ArmyGroupGiveUpStar_traits_descriptor();
inline const ::std::string& Radio_ArmyGroupGiveUpStar_traits_Name(Radio_ArmyGroupGiveUpStar_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    Radio_ArmyGroupGiveUpStar_traits_descriptor(), value);
}
inline bool Radio_ArmyGroupGiveUpStar_traits_Parse(
    const ::std::string& name, Radio_ArmyGroupGiveUpStar_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Radio_ArmyGroupGiveUpStar_traits>(
    Radio_ArmyGroupGiveUpStar_traits_descriptor(), name, value);
}
// ===================================================================

class Radio_ArmyGroupGiveUpStar : public ::google::protobuf::Message {
 public:
  Radio_ArmyGroupGiveUpStar();
  virtual ~Radio_ArmyGroupGiveUpStar();
  
  Radio_ArmyGroupGiveUpStar(const Radio_ArmyGroupGiveUpStar& from);
  
  inline Radio_ArmyGroupGiveUpStar& operator=(const Radio_ArmyGroupGiveUpStar& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Radio_ArmyGroupGiveUpStar& default_instance();
  
  void Swap(Radio_ArmyGroupGiveUpStar* other);
  
  // implements Message ----------------------------------------------
  
  Radio_ArmyGroupGiveUpStar* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Radio_ArmyGroupGiveUpStar& from);
  void MergeFrom(const Radio_ArmyGroupGiveUpStar& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Radio_ArmyGroupGiveUpStar_traits traits;
  static const traits value = Radio_ArmyGroupGiveUpStar_traits_value;
  static inline bool traits_IsValid(int value) {
    return Radio_ArmyGroupGiveUpStar_traits_IsValid(value);
  }
  static const traits traits_MIN =
    Radio_ArmyGroupGiveUpStar_traits_traits_MIN;
  static const traits traits_MAX =
    Radio_ArmyGroupGiveUpStar_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    Radio_ArmyGroupGiveUpStar_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return Radio_ArmyGroupGiveUpStar_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return Radio_ArmyGroupGiveUpStar_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return Radio_ArmyGroupGiveUpStar_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 star_id = 1;
  inline bool has_star_id() const;
  inline void clear_star_id();
  static const int kStarIdFieldNumber = 1;
  inline ::google::protobuf::int32 star_id() const;
  inline void set_star_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.Radio_ArmyGroupGiveUpStar)
 private:
  inline void set_has_star_id();
  inline void clear_has_star_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 star_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_Radio_5fArmyGroupGiveUpStar_2eproto();
  friend void protobuf_AssignDesc_Radio_5fArmyGroupGiveUpStar_2eproto();
  friend void protobuf_ShutdownFile_Radio_5fArmyGroupGiveUpStar_2eproto();
  
  void InitAsDefaultInstance();
  static Radio_ArmyGroupGiveUpStar* default_instance_;
};
// ===================================================================


// ===================================================================

// Radio_ArmyGroupGiveUpStar

// required int32 star_id = 1;
inline bool Radio_ArmyGroupGiveUpStar::has_star_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Radio_ArmyGroupGiveUpStar::set_has_star_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Radio_ArmyGroupGiveUpStar::clear_has_star_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Radio_ArmyGroupGiveUpStar::clear_star_id() {
  star_id_ = 0;
  clear_has_star_id();
}
inline ::google::protobuf::int32 Radio_ArmyGroupGiveUpStar::star_id() const {
  return star_id_;
}
inline void Radio_ArmyGroupGiveUpStar::set_star_id(::google::protobuf::int32 value) {
  set_has_star_id();
  star_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Radio_ArmyGroupGiveUpStar_traits>() {
  return ::game_connection::Radio_ArmyGroupGiveUpStar_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Radio_5fArmyGroupGiveUpStar_2eproto__INCLUDED
