// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radio_DailyBossBonus.proto

#ifndef PROTOBUF_Radio_5fDailyBossBonus_2eproto__INCLUDED
#define PROTOBUF_Radio_5fDailyBossBonus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Radio_5fDailyBossBonus_2eproto();
void protobuf_AssignDesc_Radio_5fDailyBossBonus_2eproto();
void protobuf_ShutdownFile_Radio_5fDailyBossBonus_2eproto();

class Radio_DailyBossBonus;
class Radio_DailyBossBonus_Reward;

enum Radio_DailyBossBonus_traits {
  Radio_DailyBossBonus_traits_value = 3154
};
bool Radio_DailyBossBonus_traits_IsValid(int value);
const Radio_DailyBossBonus_traits Radio_DailyBossBonus_traits_traits_MIN = Radio_DailyBossBonus_traits_value;
const Radio_DailyBossBonus_traits Radio_DailyBossBonus_traits_traits_MAX = Radio_DailyBossBonus_traits_value;
const int Radio_DailyBossBonus_traits_traits_ARRAYSIZE = Radio_DailyBossBonus_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* Radio_DailyBossBonus_traits_descriptor();
inline const ::std::string& Radio_DailyBossBonus_traits_Name(Radio_DailyBossBonus_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    Radio_DailyBossBonus_traits_descriptor(), value);
}
inline bool Radio_DailyBossBonus_traits_Parse(
    const ::std::string& name, Radio_DailyBossBonus_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Radio_DailyBossBonus_traits>(
    Radio_DailyBossBonus_traits_descriptor(), name, value);
}
enum Radio_DailyBossBonus_AwardType {
  Radio_DailyBossBonus_AwardType_GAT_NULL = 0,
  Radio_DailyBossBonus_AwardType_GAT_MONEY = 1,
  Radio_DailyBossBonus_AwardType_GAT_PROP_OR_EQUIPMENT = 2,
  Radio_DailyBossBonus_AwardType_GAT_SCORE = 3
};
bool Radio_DailyBossBonus_AwardType_IsValid(int value);
const Radio_DailyBossBonus_AwardType Radio_DailyBossBonus_AwardType_AwardType_MIN = Radio_DailyBossBonus_AwardType_GAT_NULL;
const Radio_DailyBossBonus_AwardType Radio_DailyBossBonus_AwardType_AwardType_MAX = Radio_DailyBossBonus_AwardType_GAT_SCORE;
const int Radio_DailyBossBonus_AwardType_AwardType_ARRAYSIZE = Radio_DailyBossBonus_AwardType_AwardType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Radio_DailyBossBonus_AwardType_descriptor();
inline const ::std::string& Radio_DailyBossBonus_AwardType_Name(Radio_DailyBossBonus_AwardType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Radio_DailyBossBonus_AwardType_descriptor(), value);
}
inline bool Radio_DailyBossBonus_AwardType_Parse(
    const ::std::string& name, Radio_DailyBossBonus_AwardType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Radio_DailyBossBonus_AwardType>(
    Radio_DailyBossBonus_AwardType_descriptor(), name, value);
}
// ===================================================================

class Radio_DailyBossBonus_Reward : public ::google::protobuf::Message {
 public:
  Radio_DailyBossBonus_Reward();
  virtual ~Radio_DailyBossBonus_Reward();
  
  Radio_DailyBossBonus_Reward(const Radio_DailyBossBonus_Reward& from);
  
  inline Radio_DailyBossBonus_Reward& operator=(const Radio_DailyBossBonus_Reward& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Radio_DailyBossBonus_Reward& default_instance();
  
  void Swap(Radio_DailyBossBonus_Reward* other);
  
  // implements Message ----------------------------------------------
  
  Radio_DailyBossBonus_Reward* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Radio_DailyBossBonus_Reward& from);
  void MergeFrom(const Radio_DailyBossBonus_Reward& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // required int32 object_id = 2;
  inline bool has_object_id() const;
  inline void clear_object_id();
  static const int kObjectIdFieldNumber = 2;
  inline ::google::protobuf::int32 object_id() const;
  inline void set_object_id(::google::protobuf::int32 value);
  
  // required int32 size = 3;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 3;
  inline ::google::protobuf::int32 size() const;
  inline void set_size(::google::protobuf::int32 value);
  
  // required int32 order = 4;
  inline bool has_order() const;
  inline void clear_order();
  static const int kOrderFieldNumber = 4;
  inline ::google::protobuf::int32 order() const;
  inline void set_order(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.Radio_DailyBossBonus.Reward)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_object_id();
  inline void clear_has_object_id();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_order();
  inline void clear_has_order();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 object_id_;
  ::google::protobuf::int32 size_;
  ::google::protobuf::int32 order_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Radio_5fDailyBossBonus_2eproto();
  friend void protobuf_AssignDesc_Radio_5fDailyBossBonus_2eproto();
  friend void protobuf_ShutdownFile_Radio_5fDailyBossBonus_2eproto();
  
  void InitAsDefaultInstance();
  static Radio_DailyBossBonus_Reward* default_instance_;
};
// -------------------------------------------------------------------

class Radio_DailyBossBonus : public ::google::protobuf::Message {
 public:
  Radio_DailyBossBonus();
  virtual ~Radio_DailyBossBonus();
  
  Radio_DailyBossBonus(const Radio_DailyBossBonus& from);
  
  inline Radio_DailyBossBonus& operator=(const Radio_DailyBossBonus& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Radio_DailyBossBonus& default_instance();
  
  void Swap(Radio_DailyBossBonus* other);
  
  // implements Message ----------------------------------------------
  
  Radio_DailyBossBonus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Radio_DailyBossBonus& from);
  void MergeFrom(const Radio_DailyBossBonus& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Radio_DailyBossBonus_Reward Reward;
  
  typedef Radio_DailyBossBonus_traits traits;
  static const traits value = Radio_DailyBossBonus_traits_value;
  static inline bool traits_IsValid(int value) {
    return Radio_DailyBossBonus_traits_IsValid(value);
  }
  static const traits traits_MIN =
    Radio_DailyBossBonus_traits_traits_MIN;
  static const traits traits_MAX =
    Radio_DailyBossBonus_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    Radio_DailyBossBonus_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return Radio_DailyBossBonus_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return Radio_DailyBossBonus_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return Radio_DailyBossBonus_traits_Parse(name, value);
  }
  
  typedef Radio_DailyBossBonus_AwardType AwardType;
  static const AwardType GAT_NULL = Radio_DailyBossBonus_AwardType_GAT_NULL;
  static const AwardType GAT_MONEY = Radio_DailyBossBonus_AwardType_GAT_MONEY;
  static const AwardType GAT_PROP_OR_EQUIPMENT = Radio_DailyBossBonus_AwardType_GAT_PROP_OR_EQUIPMENT;
  static const AwardType GAT_SCORE = Radio_DailyBossBonus_AwardType_GAT_SCORE;
  static inline bool AwardType_IsValid(int value) {
    return Radio_DailyBossBonus_AwardType_IsValid(value);
  }
  static const AwardType AwardType_MIN =
    Radio_DailyBossBonus_AwardType_AwardType_MIN;
  static const AwardType AwardType_MAX =
    Radio_DailyBossBonus_AwardType_AwardType_MAX;
  static const int AwardType_ARRAYSIZE =
    Radio_DailyBossBonus_AwardType_AwardType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  AwardType_descriptor() {
    return Radio_DailyBossBonus_AwardType_descriptor();
  }
  static inline const ::std::string& AwardType_Name(AwardType value) {
    return Radio_DailyBossBonus_AwardType_Name(value);
  }
  static inline bool AwardType_Parse(const ::std::string& name,
      AwardType* value) {
    return Radio_DailyBossBonus_AwardType_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);
  
  // required int32 boss_id = 2;
  inline bool has_boss_id() const;
  inline void clear_boss_id();
  static const int kBossIdFieldNumber = 2;
  inline ::google::protobuf::int32 boss_id() const;
  inline void set_boss_id(::google::protobuf::int32 value);
  
  // repeated .game_connection.Radio_DailyBossBonus.Reward award = 3;
  inline int award_size() const;
  inline void clear_award();
  static const int kAwardFieldNumber = 3;
  inline const ::game_connection::Radio_DailyBossBonus_Reward& award(int index) const;
  inline ::game_connection::Radio_DailyBossBonus_Reward* mutable_award(int index);
  inline ::game_connection::Radio_DailyBossBonus_Reward* add_award();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::Radio_DailyBossBonus_Reward >&
      award() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::Radio_DailyBossBonus_Reward >*
      mutable_award();
  
  // @@protoc_insertion_point(class_scope:game_connection.Radio_DailyBossBonus)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_boss_id();
  inline void clear_has_boss_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 player_id_;
  ::google::protobuf::int32 boss_id_;
  ::google::protobuf::RepeatedPtrField< ::game_connection::Radio_DailyBossBonus_Reward > award_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_Radio_5fDailyBossBonus_2eproto();
  friend void protobuf_AssignDesc_Radio_5fDailyBossBonus_2eproto();
  friend void protobuf_ShutdownFile_Radio_5fDailyBossBonus_2eproto();
  
  void InitAsDefaultInstance();
  static Radio_DailyBossBonus* default_instance_;
};
// ===================================================================


// ===================================================================

// Radio_DailyBossBonus_Reward

// required int32 type = 1;
inline bool Radio_DailyBossBonus_Reward::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Radio_DailyBossBonus_Reward::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Radio_DailyBossBonus_Reward::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Radio_DailyBossBonus_Reward::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus_Reward::type() const {
  return type_;
}
inline void Radio_DailyBossBonus_Reward::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// required int32 object_id = 2;
inline bool Radio_DailyBossBonus_Reward::has_object_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Radio_DailyBossBonus_Reward::set_has_object_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Radio_DailyBossBonus_Reward::clear_has_object_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Radio_DailyBossBonus_Reward::clear_object_id() {
  object_id_ = 0;
  clear_has_object_id();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus_Reward::object_id() const {
  return object_id_;
}
inline void Radio_DailyBossBonus_Reward::set_object_id(::google::protobuf::int32 value) {
  set_has_object_id();
  object_id_ = value;
}

// required int32 size = 3;
inline bool Radio_DailyBossBonus_Reward::has_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Radio_DailyBossBonus_Reward::set_has_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Radio_DailyBossBonus_Reward::clear_has_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Radio_DailyBossBonus_Reward::clear_size() {
  size_ = 0;
  clear_has_size();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus_Reward::size() const {
  return size_;
}
inline void Radio_DailyBossBonus_Reward::set_size(::google::protobuf::int32 value) {
  set_has_size();
  size_ = value;
}

// required int32 order = 4;
inline bool Radio_DailyBossBonus_Reward::has_order() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Radio_DailyBossBonus_Reward::set_has_order() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Radio_DailyBossBonus_Reward::clear_has_order() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Radio_DailyBossBonus_Reward::clear_order() {
  order_ = 0;
  clear_has_order();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus_Reward::order() const {
  return order_;
}
inline void Radio_DailyBossBonus_Reward::set_order(::google::protobuf::int32 value) {
  set_has_order();
  order_ = value;
}

// -------------------------------------------------------------------

// Radio_DailyBossBonus

// required int32 player_id = 1;
inline bool Radio_DailyBossBonus::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Radio_DailyBossBonus::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Radio_DailyBossBonus::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Radio_DailyBossBonus::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus::player_id() const {
  return player_id_;
}
inline void Radio_DailyBossBonus::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// required int32 boss_id = 2;
inline bool Radio_DailyBossBonus::has_boss_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Radio_DailyBossBonus::set_has_boss_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Radio_DailyBossBonus::clear_has_boss_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Radio_DailyBossBonus::clear_boss_id() {
  boss_id_ = 0;
  clear_has_boss_id();
}
inline ::google::protobuf::int32 Radio_DailyBossBonus::boss_id() const {
  return boss_id_;
}
inline void Radio_DailyBossBonus::set_boss_id(::google::protobuf::int32 value) {
  set_has_boss_id();
  boss_id_ = value;
}

// repeated .game_connection.Radio_DailyBossBonus.Reward award = 3;
inline int Radio_DailyBossBonus::award_size() const {
  return award_.size();
}
inline void Radio_DailyBossBonus::clear_award() {
  award_.Clear();
}
inline const ::game_connection::Radio_DailyBossBonus_Reward& Radio_DailyBossBonus::award(int index) const {
  return award_.Get(index);
}
inline ::game_connection::Radio_DailyBossBonus_Reward* Radio_DailyBossBonus::mutable_award(int index) {
  return award_.Mutable(index);
}
inline ::game_connection::Radio_DailyBossBonus_Reward* Radio_DailyBossBonus::add_award() {
  return award_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::Radio_DailyBossBonus_Reward >&
Radio_DailyBossBonus::award() const {
  return award_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::Radio_DailyBossBonus_Reward >*
Radio_DailyBossBonus::mutable_award() {
  return &award_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Radio_DailyBossBonus_traits>() {
  return ::game_connection::Radio_DailyBossBonus_traits_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::Radio_DailyBossBonus_AwardType>() {
  return ::game_connection::Radio_DailyBossBonus_AwardType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Radio_5fDailyBossBonus_2eproto__INCLUDED
