// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerTime.proto

#ifndef PROTOBUF_ServerTime_2eproto__INCLUDED
#define PROTOBUF_ServerTime_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerTime_2eproto();
void protobuf_AssignDesc_ServerTime_2eproto();
void protobuf_ShutdownFile_ServerTime_2eproto();

class ServerTime;

enum ServerTime_traits {
  ServerTime_traits_value = 3083
};
bool ServerTime_traits_IsValid(int value);
const ServerTime_traits ServerTime_traits_traits_MIN = ServerTime_traits_value;
const ServerTime_traits ServerTime_traits_traits_MAX = ServerTime_traits_value;
const int ServerTime_traits_traits_ARRAYSIZE = ServerTime_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* ServerTime_traits_descriptor();
inline const ::std::string& ServerTime_traits_Name(ServerTime_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    ServerTime_traits_descriptor(), value);
}
inline bool ServerTime_traits_Parse(
    const ::std::string& name, ServerTime_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ServerTime_traits>(
    ServerTime_traits_descriptor(), name, value);
}
// ===================================================================

class ServerTime : public ::google::protobuf::Message {
 public:
  ServerTime();
  virtual ~ServerTime();
  
  ServerTime(const ServerTime& from);
  
  inline ServerTime& operator=(const ServerTime& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerTime& default_instance();
  
  void Swap(ServerTime* other);
  
  // implements Message ----------------------------------------------
  
  ServerTime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerTime& from);
  void MergeFrom(const ServerTime& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ServerTime_traits traits;
  static const traits value = ServerTime_traits_value;
  static inline bool traits_IsValid(int value) {
    return ServerTime_traits_IsValid(value);
  }
  static const traits traits_MIN =
    ServerTime_traits_traits_MIN;
  static const traits traits_MAX =
    ServerTime_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    ServerTime_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return ServerTime_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return ServerTime_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return ServerTime_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int64 tick = 1;
  inline bool has_tick() const;
  inline void clear_tick();
  static const int kTickFieldNumber = 1;
  inline ::google::protobuf::int64 tick() const;
  inline void set_tick(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.ServerTime)
 private:
  inline void set_has_tick();
  inline void clear_has_tick();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 tick_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ServerTime_2eproto();
  friend void protobuf_AssignDesc_ServerTime_2eproto();
  friend void protobuf_ShutdownFile_ServerTime_2eproto();
  
  void InitAsDefaultInstance();
  static ServerTime* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerTime

// required int64 tick = 1;
inline bool ServerTime::has_tick() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerTime::set_has_tick() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerTime::clear_has_tick() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerTime::clear_tick() {
  tick_ = GOOGLE_LONGLONG(0);
  clear_has_tick();
}
inline ::google::protobuf::int64 ServerTime::tick() const {
  return tick_;
}
inline void ServerTime::set_tick(::google::protobuf::int64 value) {
  set_has_tick();
  tick_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::ServerTime_traits>() {
  return ::game_connection::ServerTime_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerTime_2eproto__INCLUDED
