// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityTreasureInformation.proto

#ifndef PROTOBUF_UnityTreasureInformation_2eproto__INCLUDED
#define PROTOBUF_UnityTreasureInformation_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityTreasureInformation_2eproto();
void protobuf_AssignDesc_UnityTreasureInformation_2eproto();
void protobuf_ShutdownFile_UnityTreasureInformation_2eproto();

class UnityTreasureInformation;

enum UnityTreasureInformation_traits {
  UnityTreasureInformation_traits_value = 3363
};
bool UnityTreasureInformation_traits_IsValid(int value);
const UnityTreasureInformation_traits UnityTreasureInformation_traits_traits_MIN = UnityTreasureInformation_traits_value;
const UnityTreasureInformation_traits UnityTreasureInformation_traits_traits_MAX = UnityTreasureInformation_traits_value;
const int UnityTreasureInformation_traits_traits_ARRAYSIZE = UnityTreasureInformation_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityTreasureInformation_traits_descriptor();
inline const ::std::string& UnityTreasureInformation_traits_Name(UnityTreasureInformation_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityTreasureInformation_traits_descriptor(), value);
}
inline bool UnityTreasureInformation_traits_Parse(
    const ::std::string& name, UnityTreasureInformation_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityTreasureInformation_traits>(
    UnityTreasureInformation_traits_descriptor(), name, value);
}
// ===================================================================

class UnityTreasureInformation : public ::google::protobuf::Message {
 public:
  UnityTreasureInformation();
  virtual ~UnityTreasureInformation();
  
  UnityTreasureInformation(const UnityTreasureInformation& from);
  
  inline UnityTreasureInformation& operator=(const UnityTreasureInformation& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityTreasureInformation& default_instance();
  
  void Swap(UnityTreasureInformation* other);
  
  // implements Message ----------------------------------------------
  
  UnityTreasureInformation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityTreasureInformation& from);
  void MergeFrom(const UnityTreasureInformation& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityTreasureInformation_traits traits;
  static const traits value = UnityTreasureInformation_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityTreasureInformation_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityTreasureInformation_traits_traits_MIN;
  static const traits traits_MAX =
    UnityTreasureInformation_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityTreasureInformation_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityTreasureInformation_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityTreasureInformation_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityTreasureInformation_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required bytes information = 1;
  inline bool has_information() const;
  inline void clear_information();
  static const int kInformationFieldNumber = 1;
  inline const ::std::string& information() const;
  inline void set_information(const ::std::string& value);
  inline void set_information(const char* value);
  inline void set_information(const void* value, size_t size);
  inline ::std::string* mutable_information();
  inline ::std::string* release_information();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityTreasureInformation)
 private:
  inline void set_has_information();
  inline void clear_has_information();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* information_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityTreasureInformation_2eproto();
  friend void protobuf_AssignDesc_UnityTreasureInformation_2eproto();
  friend void protobuf_ShutdownFile_UnityTreasureInformation_2eproto();
  
  void InitAsDefaultInstance();
  static UnityTreasureInformation* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityTreasureInformation

// required bytes information = 1;
inline bool UnityTreasureInformation::has_information() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityTreasureInformation::set_has_information() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityTreasureInformation::clear_has_information() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityTreasureInformation::clear_information() {
  if (information_ != &::google::protobuf::internal::kEmptyString) {
    information_->clear();
  }
  clear_has_information();
}
inline const ::std::string& UnityTreasureInformation::information() const {
  return *information_;
}
inline void UnityTreasureInformation::set_information(const ::std::string& value) {
  set_has_information();
  if (information_ == &::google::protobuf::internal::kEmptyString) {
    information_ = new ::std::string;
  }
  information_->assign(value);
}
inline void UnityTreasureInformation::set_information(const char* value) {
  set_has_information();
  if (information_ == &::google::protobuf::internal::kEmptyString) {
    information_ = new ::std::string;
  }
  information_->assign(value);
}
inline void UnityTreasureInformation::set_information(const void* value, size_t size) {
  set_has_information();
  if (information_ == &::google::protobuf::internal::kEmptyString) {
    information_ = new ::std::string;
  }
  information_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UnityTreasureInformation::mutable_information() {
  set_has_information();
  if (information_ == &::google::protobuf::internal::kEmptyString) {
    information_ = new ::std::string;
  }
  return information_;
}
inline ::std::string* UnityTreasureInformation::release_information() {
  clear_has_information();
  if (information_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = information_;
    information_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityTreasureInformation_traits>() {
  return ::game_connection::UnityTreasureInformation_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityTreasureInformation_2eproto__INCLUDED
