// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityGhostOffline.proto

#ifndef PROTOBUF_UnityGhostOffline_2eproto__INCLUDED
#define PROTOBUF_UnityGhostOffline_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityGhostOffline_2eproto();
void protobuf_AssignDesc_UnityGhostOffline_2eproto();
void protobuf_ShutdownFile_UnityGhostOffline_2eproto();

class UnityGhostOffline;

enum UnityGhostOffline_traits {
  UnityGhostOffline_traits_value = 3356
};
bool UnityGhostOffline_traits_IsValid(int value);
const UnityGhostOffline_traits UnityGhostOffline_traits_traits_MIN = UnityGhostOffline_traits_value;
const UnityGhostOffline_traits UnityGhostOffline_traits_traits_MAX = UnityGhostOffline_traits_value;
const int UnityGhostOffline_traits_traits_ARRAYSIZE = UnityGhostOffline_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityGhostOffline_traits_descriptor();
inline const ::std::string& UnityGhostOffline_traits_Name(UnityGhostOffline_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityGhostOffline_traits_descriptor(), value);
}
inline bool UnityGhostOffline_traits_Parse(
    const ::std::string& name, UnityGhostOffline_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityGhostOffline_traits>(
    UnityGhostOffline_traits_descriptor(), name, value);
}
// ===================================================================

class UnityGhostOffline : public ::google::protobuf::Message {
 public:
  UnityGhostOffline();
  virtual ~UnityGhostOffline();
  
  UnityGhostOffline(const UnityGhostOffline& from);
  
  inline UnityGhostOffline& operator=(const UnityGhostOffline& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityGhostOffline& default_instance();
  
  void Swap(UnityGhostOffline* other);
  
  // implements Message ----------------------------------------------
  
  UnityGhostOffline* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityGhostOffline& from);
  void MergeFrom(const UnityGhostOffline& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityGhostOffline_traits traits;
  static const traits value = UnityGhostOffline_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityGhostOffline_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityGhostOffline_traits_traits_MIN;
  static const traits traits_MAX =
    UnityGhostOffline_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityGhostOffline_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityGhostOffline_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityGhostOffline_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityGhostOffline_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityGhostOffline)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityGhostOffline_2eproto();
  friend void protobuf_AssignDesc_UnityGhostOffline_2eproto();
  friend void protobuf_ShutdownFile_UnityGhostOffline_2eproto();
  
  void InitAsDefaultInstance();
  static UnityGhostOffline* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityGhostOffline

// required int32 id = 1;
inline bool UnityGhostOffline::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityGhostOffline::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityGhostOffline::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityGhostOffline::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 UnityGhostOffline::id() const {
  return id_;
}
inline void UnityGhostOffline::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityGhostOffline_traits>() {
  return ::game_connection::UnityGhostOffline_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityGhostOffline_2eproto__INCLUDED
