// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityHallChat.proto

#ifndef PROTOBUF_UnityHallChat_2eproto__INCLUDED
#define PROTOBUF_UnityHallChat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityHallChat_2eproto();
void protobuf_AssignDesc_UnityHallChat_2eproto();
void protobuf_ShutdownFile_UnityHallChat_2eproto();

class UnityHallChat;

enum UnityHallChat_traits {
  UnityHallChat_traits_value = 3408
};
bool UnityHallChat_traits_IsValid(int value);
const UnityHallChat_traits UnityHallChat_traits_traits_MIN = UnityHallChat_traits_value;
const UnityHallChat_traits UnityHallChat_traits_traits_MAX = UnityHallChat_traits_value;
const int UnityHallChat_traits_traits_ARRAYSIZE = UnityHallChat_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityHallChat_traits_descriptor();
inline const ::std::string& UnityHallChat_traits_Name(UnityHallChat_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityHallChat_traits_descriptor(), value);
}
inline bool UnityHallChat_traits_Parse(
    const ::std::string& name, UnityHallChat_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityHallChat_traits>(
    UnityHallChat_traits_descriptor(), name, value);
}
// ===================================================================

class UnityHallChat : public ::google::protobuf::Message {
 public:
  UnityHallChat();
  virtual ~UnityHallChat();
  
  UnityHallChat(const UnityHallChat& from);
  
  inline UnityHallChat& operator=(const UnityHallChat& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityHallChat& default_instance();
  
  void Swap(UnityHallChat* other);
  
  // implements Message ----------------------------------------------
  
  UnityHallChat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityHallChat& from);
  void MergeFrom(const UnityHallChat& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityHallChat_traits traits;
  static const traits value = UnityHallChat_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityHallChat_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityHallChat_traits_traits_MIN;
  static const traits traits_MAX =
    UnityHallChat_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityHallChat_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityHallChat_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityHallChat_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityHallChat_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 from_player = 1;
  inline bool has_from_player() const;
  inline void clear_from_player();
  static const int kFromPlayerFieldNumber = 1;
  inline ::google::protobuf::int32 from_player() const;
  inline void set_from_player(::google::protobuf::int32 value);
  
  // required bytes infomation = 2;
  inline bool has_infomation() const;
  inline void clear_infomation();
  static const int kInfomationFieldNumber = 2;
  inline const ::std::string& infomation() const;
  inline void set_infomation(const ::std::string& value);
  inline void set_infomation(const char* value);
  inline void set_infomation(const void* value, size_t size);
  inline ::std::string* mutable_infomation();
  inline ::std::string* release_infomation();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityHallChat)
 private:
  inline void set_has_from_player();
  inline void clear_has_from_player();
  inline void set_has_infomation();
  inline void clear_has_infomation();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* infomation_;
  ::google::protobuf::int32 from_player_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityHallChat_2eproto();
  friend void protobuf_AssignDesc_UnityHallChat_2eproto();
  friend void protobuf_ShutdownFile_UnityHallChat_2eproto();
  
  void InitAsDefaultInstance();
  static UnityHallChat* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityHallChat

// required int32 from_player = 1;
inline bool UnityHallChat::has_from_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityHallChat::set_has_from_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityHallChat::clear_has_from_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityHallChat::clear_from_player() {
  from_player_ = 0;
  clear_has_from_player();
}
inline ::google::protobuf::int32 UnityHallChat::from_player() const {
  return from_player_;
}
inline void UnityHallChat::set_from_player(::google::protobuf::int32 value) {
  set_has_from_player();
  from_player_ = value;
}

// required bytes infomation = 2;
inline bool UnityHallChat::has_infomation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnityHallChat::set_has_infomation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnityHallChat::clear_has_infomation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnityHallChat::clear_infomation() {
  if (infomation_ != &::google::protobuf::internal::kEmptyString) {
    infomation_->clear();
  }
  clear_has_infomation();
}
inline const ::std::string& UnityHallChat::infomation() const {
  return *infomation_;
}
inline void UnityHallChat::set_infomation(const ::std::string& value) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(value);
}
inline void UnityHallChat::set_infomation(const char* value) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(value);
}
inline void UnityHallChat::set_infomation(const void* value, size_t size) {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  infomation_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UnityHallChat::mutable_infomation() {
  set_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    infomation_ = new ::std::string;
  }
  return infomation_;
}
inline ::std::string* UnityHallChat::release_infomation() {
  clear_has_infomation();
  if (infomation_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = infomation_;
    infomation_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityHallChat_traits>() {
  return ::game_connection::UnityHallChat_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityHallChat_2eproto__INCLUDED
