// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityUnactiveRecharging.proto

#ifndef PROTOBUF_UnityUnactiveRecharging_2eproto__INCLUDED
#define PROTOBUF_UnityUnactiveRecharging_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityUnactiveRecharging_2eproto();
void protobuf_AssignDesc_UnityUnactiveRecharging_2eproto();
void protobuf_ShutdownFile_UnityUnactiveRecharging_2eproto();

class UnityUnactiveRecharging;

enum UnityUnactiveRecharging_traits {
  UnityUnactiveRecharging_traits_value = 3256
};
bool UnityUnactiveRecharging_traits_IsValid(int value);
const UnityUnactiveRecharging_traits UnityUnactiveRecharging_traits_traits_MIN = UnityUnactiveRecharging_traits_value;
const UnityUnactiveRecharging_traits UnityUnactiveRecharging_traits_traits_MAX = UnityUnactiveRecharging_traits_value;
const int UnityUnactiveRecharging_traits_traits_ARRAYSIZE = UnityUnactiveRecharging_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityUnactiveRecharging_traits_descriptor();
inline const ::std::string& UnityUnactiveRecharging_traits_Name(UnityUnactiveRecharging_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityUnactiveRecharging_traits_descriptor(), value);
}
inline bool UnityUnactiveRecharging_traits_Parse(
    const ::std::string& name, UnityUnactiveRecharging_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityUnactiveRecharging_traits>(
    UnityUnactiveRecharging_traits_descriptor(), name, value);
}
// ===================================================================

class UnityUnactiveRecharging : public ::google::protobuf::Message {
 public:
  UnityUnactiveRecharging();
  virtual ~UnityUnactiveRecharging();
  
  UnityUnactiveRecharging(const UnityUnactiveRecharging& from);
  
  inline UnityUnactiveRecharging& operator=(const UnityUnactiveRecharging& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityUnactiveRecharging& default_instance();
  
  void Swap(UnityUnactiveRecharging* other);
  
  // implements Message ----------------------------------------------
  
  UnityUnactiveRecharging* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityUnactiveRecharging& from);
  void MergeFrom(const UnityUnactiveRecharging& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityUnactiveRecharging_traits traits;
  static const traits value = UnityUnactiveRecharging_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityUnactiveRecharging_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityUnactiveRecharging_traits_traits_MIN;
  static const traits traits_MAX =
    UnityUnactiveRecharging_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityUnactiveRecharging_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityUnactiveRecharging_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityUnactiveRecharging_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityUnactiveRecharging_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityUnactiveRecharging)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_UnityUnactiveRecharging_2eproto();
  friend void protobuf_AssignDesc_UnityUnactiveRecharging_2eproto();
  friend void protobuf_ShutdownFile_UnityUnactiveRecharging_2eproto();
  
  void InitAsDefaultInstance();
  static UnityUnactiveRecharging* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityUnactiveRecharging


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityUnactiveRecharging_traits>() {
  return ::game_connection::UnityUnactiveRecharging_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityUnactiveRecharging_2eproto__INCLUDED
