// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityAdjuntantInformation.proto

#ifndef PROTOBUF_UnityAdjuntantInformation_2eproto__INCLUDED
#define PROTOBUF_UnityAdjuntantInformation_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityAdjuntantInformation_2eproto();
void protobuf_AssignDesc_UnityAdjuntantInformation_2eproto();
void protobuf_ShutdownFile_UnityAdjuntantInformation_2eproto();

class UnityAdjuntantInformation;
class UnityAdjuntantInformation_Adjuntant;
class UnityAdjuntantInformation_Adjuntant_Skill;
class UnityAdjuntantInformation_Adjuntant_Equipment;

enum UnityAdjuntantInformation_traits {
  UnityAdjuntantInformation_traits_value = 4426
};
bool UnityAdjuntantInformation_traits_IsValid(int value);
const UnityAdjuntantInformation_traits UnityAdjuntantInformation_traits_traits_MIN = UnityAdjuntantInformation_traits_value;
const UnityAdjuntantInformation_traits UnityAdjuntantInformation_traits_traits_MAX = UnityAdjuntantInformation_traits_value;
const int UnityAdjuntantInformation_traits_traits_ARRAYSIZE = UnityAdjuntantInformation_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityAdjuntantInformation_traits_descriptor();
inline const ::std::string& UnityAdjuntantInformation_traits_Name(UnityAdjuntantInformation_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityAdjuntantInformation_traits_descriptor(), value);
}
inline bool UnityAdjuntantInformation_traits_Parse(
    const ::std::string& name, UnityAdjuntantInformation_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityAdjuntantInformation_traits>(
    UnityAdjuntantInformation_traits_descriptor(), name, value);
}
// ===================================================================

class UnityAdjuntantInformation_Adjuntant_Skill : public ::google::protobuf::Message {
 public:
  UnityAdjuntantInformation_Adjuntant_Skill();
  virtual ~UnityAdjuntantInformation_Adjuntant_Skill();
  
  UnityAdjuntantInformation_Adjuntant_Skill(const UnityAdjuntantInformation_Adjuntant_Skill& from);
  
  inline UnityAdjuntantInformation_Adjuntant_Skill& operator=(const UnityAdjuntantInformation_Adjuntant_Skill& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityAdjuntantInformation_Adjuntant_Skill& default_instance();
  
  void Swap(UnityAdjuntantInformation_Adjuntant_Skill* other);
  
  // implements Message ----------------------------------------------
  
  UnityAdjuntantInformation_Adjuntant_Skill* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityAdjuntantInformation_Adjuntant_Skill& from);
  void MergeFrom(const UnityAdjuntantInformation_Adjuntant_Skill& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // required int32 grade = 2;
  inline bool has_grade() const;
  inline void clear_grade();
  static const int kGradeFieldNumber = 2;
  inline ::google::protobuf::int32 grade() const;
  inline void set_grade(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityAdjuntantInformation.Adjuntant.Skill)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_grade();
  inline void clear_has_grade();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 grade_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_AssignDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_ShutdownFile_UnityAdjuntantInformation_2eproto();
  
  void InitAsDefaultInstance();
  static UnityAdjuntantInformation_Adjuntant_Skill* default_instance_;
};
// -------------------------------------------------------------------

class UnityAdjuntantInformation_Adjuntant_Equipment : public ::google::protobuf::Message {
 public:
  UnityAdjuntantInformation_Adjuntant_Equipment();
  virtual ~UnityAdjuntantInformation_Adjuntant_Equipment();
  
  UnityAdjuntantInformation_Adjuntant_Equipment(const UnityAdjuntantInformation_Adjuntant_Equipment& from);
  
  inline UnityAdjuntantInformation_Adjuntant_Equipment& operator=(const UnityAdjuntantInformation_Adjuntant_Equipment& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityAdjuntantInformation_Adjuntant_Equipment& default_instance();
  
  void Swap(UnityAdjuntantInformation_Adjuntant_Equipment* other);
  
  // implements Message ----------------------------------------------
  
  UnityAdjuntantInformation_Adjuntant_Equipment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityAdjuntantInformation_Adjuntant_Equipment& from);
  void MergeFrom(const UnityAdjuntantInformation_Adjuntant_Equipment& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 item_id = 1;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 1;
  inline ::google::protobuf::int32 item_id() const;
  inline void set_item_id(::google::protobuf::int32 value);
  
  // required int32 main_attribute = 2;
  inline bool has_main_attribute() const;
  inline void clear_main_attribute();
  static const int kMainAttributeFieldNumber = 2;
  inline ::google::protobuf::int32 main_attribute() const;
  inline void set_main_attribute(::google::protobuf::int32 value);
  
  // required int32 second_attribute = 3;
  inline bool has_second_attribute() const;
  inline void clear_second_attribute();
  static const int kSecondAttributeFieldNumber = 3;
  inline ::google::protobuf::int32 second_attribute() const;
  inline void set_second_attribute(::google::protobuf::int32 value);
  
  // required int32 star_level = 4;
  inline bool has_star_level() const;
  inline void clear_star_level();
  static const int kStarLevelFieldNumber = 4;
  inline ::google::protobuf::int32 star_level() const;
  inline void set_star_level(::google::protobuf::int32 value);
  
  // required int32 stone = 5;
  inline bool has_stone() const;
  inline void clear_stone();
  static const int kStoneFieldNumber = 5;
  inline ::google::protobuf::int32 stone() const;
  inline void set_stone(::google::protobuf::int32 value);
  
  // required int32 grade_id = 6;
  inline bool has_grade_id() const;
  inline void clear_grade_id();
  static const int kGradeIdFieldNumber = 6;
  inline ::google::protobuf::int32 grade_id() const;
  inline void set_grade_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityAdjuntantInformation.Adjuntant.Equipment)
 private:
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_main_attribute();
  inline void clear_has_main_attribute();
  inline void set_has_second_attribute();
  inline void clear_has_second_attribute();
  inline void set_has_star_level();
  inline void clear_has_star_level();
  inline void set_has_stone();
  inline void clear_has_stone();
  inline void set_has_grade_id();
  inline void clear_has_grade_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 item_id_;
  ::google::protobuf::int32 main_attribute_;
  ::google::protobuf::int32 second_attribute_;
  ::google::protobuf::int32 star_level_;
  ::google::protobuf::int32 stone_;
  ::google::protobuf::int32 grade_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_AssignDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_ShutdownFile_UnityAdjuntantInformation_2eproto();
  
  void InitAsDefaultInstance();
  static UnityAdjuntantInformation_Adjuntant_Equipment* default_instance_;
};
// -------------------------------------------------------------------

class UnityAdjuntantInformation_Adjuntant : public ::google::protobuf::Message {
 public:
  UnityAdjuntantInformation_Adjuntant();
  virtual ~UnityAdjuntantInformation_Adjuntant();
  
  UnityAdjuntantInformation_Adjuntant(const UnityAdjuntantInformation_Adjuntant& from);
  
  inline UnityAdjuntantInformation_Adjuntant& operator=(const UnityAdjuntantInformation_Adjuntant& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityAdjuntantInformation_Adjuntant& default_instance();
  
  void Swap(UnityAdjuntantInformation_Adjuntant* other);
  
  // implements Message ----------------------------------------------
  
  UnityAdjuntantInformation_Adjuntant* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityAdjuntantInformation_Adjuntant& from);
  void MergeFrom(const UnityAdjuntantInformation_Adjuntant& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityAdjuntantInformation_Adjuntant_Skill Skill;
  typedef UnityAdjuntantInformation_Adjuntant_Equipment Equipment;
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 intimacy = 2;
  inline bool has_intimacy() const;
  inline void clear_intimacy();
  static const int kIntimacyFieldNumber = 2;
  inline ::google::protobuf::int32 intimacy() const;
  inline void set_intimacy(::google::protobuf::int32 value);
  
  // required int32 order = 3;
  inline bool has_order() const;
  inline void clear_order();
  static const int kOrderFieldNumber = 3;
  inline ::google::protobuf::int32 order() const;
  inline void set_order(::google::protobuf::int32 value);
  
  // required int32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);
  
  // required int32 location = 5;
  inline bool has_location() const;
  inline void clear_location();
  static const int kLocationFieldNumber = 5;
  inline ::google::protobuf::int32 location() const;
  inline void set_location(::google::protobuf::int32 value);
  
  // repeated .game_connection.UnityAdjuntantInformation.Adjuntant.Skill skill = 6;
  inline int skill_size() const;
  inline void clear_skill();
  static const int kSkillFieldNumber = 6;
  inline const ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill& skill(int index) const;
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill* mutable_skill(int index);
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill* add_skill();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill >&
      skill() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill >*
      mutable_skill();
  
  // repeated .game_connection.UnityAdjuntantInformation.Adjuntant.Equipment equipment = 7;
  inline int equipment_size() const;
  inline void clear_equipment();
  static const int kEquipmentFieldNumber = 7;
  inline const ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment& equipment(int index) const;
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment* mutable_equipment(int index);
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment* add_equipment();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment >&
      equipment() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment >*
      mutable_equipment();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityAdjuntantInformation.Adjuntant)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_intimacy();
  inline void clear_has_intimacy();
  inline void set_has_order();
  inline void clear_has_order();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_location();
  inline void clear_has_location();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 intimacy_;
  ::google::protobuf::int32 order_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill > skill_;
  ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment > equipment_;
  ::google::protobuf::int32 location_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_AssignDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_ShutdownFile_UnityAdjuntantInformation_2eproto();
  
  void InitAsDefaultInstance();
  static UnityAdjuntantInformation_Adjuntant* default_instance_;
};
// -------------------------------------------------------------------

class UnityAdjuntantInformation : public ::google::protobuf::Message {
 public:
  UnityAdjuntantInformation();
  virtual ~UnityAdjuntantInformation();
  
  UnityAdjuntantInformation(const UnityAdjuntantInformation& from);
  
  inline UnityAdjuntantInformation& operator=(const UnityAdjuntantInformation& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityAdjuntantInformation& default_instance();
  
  void Swap(UnityAdjuntantInformation* other);
  
  // implements Message ----------------------------------------------
  
  UnityAdjuntantInformation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityAdjuntantInformation& from);
  void MergeFrom(const UnityAdjuntantInformation& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityAdjuntantInformation_Adjuntant Adjuntant;
  
  typedef UnityAdjuntantInformation_traits traits;
  static const traits value = UnityAdjuntantInformation_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityAdjuntantInformation_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityAdjuntantInformation_traits_traits_MIN;
  static const traits traits_MAX =
    UnityAdjuntantInformation_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityAdjuntantInformation_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityAdjuntantInformation_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityAdjuntantInformation_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityAdjuntantInformation_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);
  
  // optional int32 server_id = 2;
  inline bool has_server_id() const;
  inline void clear_server_id();
  static const int kServerIdFieldNumber = 2;
  inline ::google::protobuf::int32 server_id() const;
  inline void set_server_id(::google::protobuf::int32 value);
  
  // repeated .game_connection.UnityAdjuntantInformation.Adjuntant adjuntant = 3;
  inline int adjuntant_size() const;
  inline void clear_adjuntant();
  static const int kAdjuntantFieldNumber = 3;
  inline const ::game_connection::UnityAdjuntantInformation_Adjuntant& adjuntant(int index) const;
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant* mutable_adjuntant(int index);
  inline ::game_connection::UnityAdjuntantInformation_Adjuntant* add_adjuntant();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant >&
      adjuntant() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant >*
      mutable_adjuntant();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityAdjuntantInformation)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_server_id();
  inline void clear_has_server_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 player_id_;
  ::google::protobuf::int32 server_id_;
  ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant > adjuntant_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_AssignDesc_UnityAdjuntantInformation_2eproto();
  friend void protobuf_ShutdownFile_UnityAdjuntantInformation_2eproto();
  
  void InitAsDefaultInstance();
  static UnityAdjuntantInformation* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityAdjuntantInformation_Adjuntant_Skill

// required int32 type = 1;
inline bool UnityAdjuntantInformation_Adjuntant_Skill::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Skill::type() const {
  return type_;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// required int32 grade = 2;
inline bool UnityAdjuntantInformation_Adjuntant_Skill::has_grade() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::set_has_grade() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::clear_has_grade() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::clear_grade() {
  grade_ = 0;
  clear_has_grade();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Skill::grade() const {
  return grade_;
}
inline void UnityAdjuntantInformation_Adjuntant_Skill::set_grade(::google::protobuf::int32 value) {
  set_has_grade();
  grade_ = value;
}

// -------------------------------------------------------------------

// UnityAdjuntantInformation_Adjuntant_Equipment

// required int32 item_id = 1;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_item_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_item_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_item_id() {
  item_id_ = 0;
  clear_has_item_id();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::item_id() const {
  return item_id_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_item_id(::google::protobuf::int32 value) {
  set_has_item_id();
  item_id_ = value;
}

// required int32 main_attribute = 2;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_main_attribute() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_main_attribute() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_main_attribute() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_main_attribute() {
  main_attribute_ = 0;
  clear_has_main_attribute();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::main_attribute() const {
  return main_attribute_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_main_attribute(::google::protobuf::int32 value) {
  set_has_main_attribute();
  main_attribute_ = value;
}

// required int32 second_attribute = 3;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_second_attribute() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_second_attribute() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_second_attribute() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_second_attribute() {
  second_attribute_ = 0;
  clear_has_second_attribute();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::second_attribute() const {
  return second_attribute_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_second_attribute(::google::protobuf::int32 value) {
  set_has_second_attribute();
  second_attribute_ = value;
}

// required int32 star_level = 4;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_star_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_star_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_star_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_star_level() {
  star_level_ = 0;
  clear_has_star_level();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::star_level() const {
  return star_level_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_star_level(::google::protobuf::int32 value) {
  set_has_star_level();
  star_level_ = value;
}

// required int32 stone = 5;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_stone() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_stone() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_stone() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_stone() {
  stone_ = 0;
  clear_has_stone();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::stone() const {
  return stone_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_stone(::google::protobuf::int32 value) {
  set_has_stone();
  stone_ = value;
}

// required int32 grade_id = 6;
inline bool UnityAdjuntantInformation_Adjuntant_Equipment::has_grade_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_has_grade_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_has_grade_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::clear_grade_id() {
  grade_id_ = 0;
  clear_has_grade_id();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant_Equipment::grade_id() const {
  return grade_id_;
}
inline void UnityAdjuntantInformation_Adjuntant_Equipment::set_grade_id(::google::protobuf::int32 value) {
  set_has_grade_id();
  grade_id_ = value;
}

// -------------------------------------------------------------------

// UnityAdjuntantInformation_Adjuntant

// required int32 id = 1;
inline bool UnityAdjuntantInformation_Adjuntant::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant::id() const {
  return id_;
}
inline void UnityAdjuntantInformation_Adjuntant::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 intimacy = 2;
inline bool UnityAdjuntantInformation_Adjuntant::has_intimacy() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant::set_has_intimacy() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_has_intimacy() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_intimacy() {
  intimacy_ = 0;
  clear_has_intimacy();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant::intimacy() const {
  return intimacy_;
}
inline void UnityAdjuntantInformation_Adjuntant::set_intimacy(::google::protobuf::int32 value) {
  set_has_intimacy();
  intimacy_ = value;
}

// required int32 order = 3;
inline bool UnityAdjuntantInformation_Adjuntant::has_order() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant::set_has_order() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_has_order() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_order() {
  order_ = 0;
  clear_has_order();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant::order() const {
  return order_;
}
inline void UnityAdjuntantInformation_Adjuntant::set_order(::google::protobuf::int32 value) {
  set_has_order();
  order_ = value;
}

// required int32 level = 4;
inline bool UnityAdjuntantInformation_Adjuntant::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant::level() const {
  return level_;
}
inline void UnityAdjuntantInformation_Adjuntant::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required int32 location = 5;
inline bool UnityAdjuntantInformation_Adjuntant::has_location() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UnityAdjuntantInformation_Adjuntant::set_has_location() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_has_location() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UnityAdjuntantInformation_Adjuntant::clear_location() {
  location_ = 0;
  clear_has_location();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation_Adjuntant::location() const {
  return location_;
}
inline void UnityAdjuntantInformation_Adjuntant::set_location(::google::protobuf::int32 value) {
  set_has_location();
  location_ = value;
}

// repeated .game_connection.UnityAdjuntantInformation.Adjuntant.Skill skill = 6;
inline int UnityAdjuntantInformation_Adjuntant::skill_size() const {
  return skill_.size();
}
inline void UnityAdjuntantInformation_Adjuntant::clear_skill() {
  skill_.Clear();
}
inline const ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill& UnityAdjuntantInformation_Adjuntant::skill(int index) const {
  return skill_.Get(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill* UnityAdjuntantInformation_Adjuntant::mutable_skill(int index) {
  return skill_.Mutable(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill* UnityAdjuntantInformation_Adjuntant::add_skill() {
  return skill_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill >&
UnityAdjuntantInformation_Adjuntant::skill() const {
  return skill_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Skill >*
UnityAdjuntantInformation_Adjuntant::mutable_skill() {
  return &skill_;
}

// repeated .game_connection.UnityAdjuntantInformation.Adjuntant.Equipment equipment = 7;
inline int UnityAdjuntantInformation_Adjuntant::equipment_size() const {
  return equipment_.size();
}
inline void UnityAdjuntantInformation_Adjuntant::clear_equipment() {
  equipment_.Clear();
}
inline const ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment& UnityAdjuntantInformation_Adjuntant::equipment(int index) const {
  return equipment_.Get(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment* UnityAdjuntantInformation_Adjuntant::mutable_equipment(int index) {
  return equipment_.Mutable(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment* UnityAdjuntantInformation_Adjuntant::add_equipment() {
  return equipment_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment >&
UnityAdjuntantInformation_Adjuntant::equipment() const {
  return equipment_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant_Equipment >*
UnityAdjuntantInformation_Adjuntant::mutable_equipment() {
  return &equipment_;
}

// -------------------------------------------------------------------

// UnityAdjuntantInformation

// required int32 player_id = 1;
inline bool UnityAdjuntantInformation::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityAdjuntantInformation::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityAdjuntantInformation::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityAdjuntantInformation::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation::player_id() const {
  return player_id_;
}
inline void UnityAdjuntantInformation::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// optional int32 server_id = 2;
inline bool UnityAdjuntantInformation::has_server_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnityAdjuntantInformation::set_has_server_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnityAdjuntantInformation::clear_has_server_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnityAdjuntantInformation::clear_server_id() {
  server_id_ = 0;
  clear_has_server_id();
}
inline ::google::protobuf::int32 UnityAdjuntantInformation::server_id() const {
  return server_id_;
}
inline void UnityAdjuntantInformation::set_server_id(::google::protobuf::int32 value) {
  set_has_server_id();
  server_id_ = value;
}

// repeated .game_connection.UnityAdjuntantInformation.Adjuntant adjuntant = 3;
inline int UnityAdjuntantInformation::adjuntant_size() const {
  return adjuntant_.size();
}
inline void UnityAdjuntantInformation::clear_adjuntant() {
  adjuntant_.Clear();
}
inline const ::game_connection::UnityAdjuntantInformation_Adjuntant& UnityAdjuntantInformation::adjuntant(int index) const {
  return adjuntant_.Get(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant* UnityAdjuntantInformation::mutable_adjuntant(int index) {
  return adjuntant_.Mutable(index);
}
inline ::game_connection::UnityAdjuntantInformation_Adjuntant* UnityAdjuntantInformation::add_adjuntant() {
  return adjuntant_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant >&
UnityAdjuntantInformation::adjuntant() const {
  return adjuntant_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnityAdjuntantInformation_Adjuntant >*
UnityAdjuntantInformation::mutable_adjuntant() {
  return &adjuntant_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityAdjuntantInformation_traits>() {
  return ::game_connection::UnityAdjuntantInformation_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityAdjuntantInformation_2eproto__INCLUDED
