// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityActiveRecharging.proto

#ifndef PROTOBUF_UnityActiveRecharging_2eproto__INCLUDED
#define PROTOBUF_UnityActiveRecharging_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityActiveRecharging_2eproto();
void protobuf_AssignDesc_UnityActiveRecharging_2eproto();
void protobuf_ShutdownFile_UnityActiveRecharging_2eproto();

class UnityActiveRecharging;

enum UnityActiveRecharging_traits {
  UnityActiveRecharging_traits_value = 3419
};
bool UnityActiveRecharging_traits_IsValid(int value);
const UnityActiveRecharging_traits UnityActiveRecharging_traits_traits_MIN = UnityActiveRecharging_traits_value;
const UnityActiveRecharging_traits UnityActiveRecharging_traits_traits_MAX = UnityActiveRecharging_traits_value;
const int UnityActiveRecharging_traits_traits_ARRAYSIZE = UnityActiveRecharging_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityActiveRecharging_traits_descriptor();
inline const ::std::string& UnityActiveRecharging_traits_Name(UnityActiveRecharging_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityActiveRecharging_traits_descriptor(), value);
}
inline bool UnityActiveRecharging_traits_Parse(
    const ::std::string& name, UnityActiveRecharging_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityActiveRecharging_traits>(
    UnityActiveRecharging_traits_descriptor(), name, value);
}
// ===================================================================

class UnityActiveRecharging : public ::google::protobuf::Message {
 public:
  UnityActiveRecharging();
  virtual ~UnityActiveRecharging();
  
  UnityActiveRecharging(const UnityActiveRecharging& from);
  
  inline UnityActiveRecharging& operator=(const UnityActiveRecharging& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityActiveRecharging& default_instance();
  
  void Swap(UnityActiveRecharging* other);
  
  // implements Message ----------------------------------------------
  
  UnityActiveRecharging* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityActiveRecharging& from);
  void MergeFrom(const UnityActiveRecharging& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityActiveRecharging_traits traits;
  static const traits value = UnityActiveRecharging_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityActiveRecharging_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityActiveRecharging_traits_traits_MIN;
  static const traits traits_MAX =
    UnityActiveRecharging_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityActiveRecharging_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityActiveRecharging_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityActiveRecharging_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityActiveRecharging_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 score = 1;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 1;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityActiveRecharging)
 private:
  inline void set_has_score();
  inline void clear_has_score();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 score_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityActiveRecharging_2eproto();
  friend void protobuf_AssignDesc_UnityActiveRecharging_2eproto();
  friend void protobuf_ShutdownFile_UnityActiveRecharging_2eproto();
  
  void InitAsDefaultInstance();
  static UnityActiveRecharging* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityActiveRecharging

// required int32 score = 1;
inline bool UnityActiveRecharging::has_score() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityActiveRecharging::set_has_score() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityActiveRecharging::clear_has_score() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityActiveRecharging::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 UnityActiveRecharging::score() const {
  return score_;
}
inline void UnityActiveRecharging::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityActiveRecharging_traits>() {
  return ::game_connection::UnityActiveRecharging_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityActiveRecharging_2eproto__INCLUDED
