// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnitySummonBossState.proto

#ifndef PROTOBUF_UnitySummonBossState_2eproto__INCLUDED
#define PROTOBUF_UnitySummonBossState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnitySummonBossState_2eproto();
void protobuf_AssignDesc_UnitySummonBossState_2eproto();
void protobuf_ShutdownFile_UnitySummonBossState_2eproto();

class UnitySummonBossState;
class UnitySummonBossState_BossInfo;

enum UnitySummonBossState_traits {
  UnitySummonBossState_traits_value = 4335
};
bool UnitySummonBossState_traits_IsValid(int value);
const UnitySummonBossState_traits UnitySummonBossState_traits_traits_MIN = UnitySummonBossState_traits_value;
const UnitySummonBossState_traits UnitySummonBossState_traits_traits_MAX = UnitySummonBossState_traits_value;
const int UnitySummonBossState_traits_traits_ARRAYSIZE = UnitySummonBossState_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnitySummonBossState_traits_descriptor();
inline const ::std::string& UnitySummonBossState_traits_Name(UnitySummonBossState_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnitySummonBossState_traits_descriptor(), value);
}
inline bool UnitySummonBossState_traits_Parse(
    const ::std::string& name, UnitySummonBossState_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnitySummonBossState_traits>(
    UnitySummonBossState_traits_descriptor(), name, value);
}
// ===================================================================

class UnitySummonBossState_BossInfo : public ::google::protobuf::Message {
 public:
  UnitySummonBossState_BossInfo();
  virtual ~UnitySummonBossState_BossInfo();
  
  UnitySummonBossState_BossInfo(const UnitySummonBossState_BossInfo& from);
  
  inline UnitySummonBossState_BossInfo& operator=(const UnitySummonBossState_BossInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnitySummonBossState_BossInfo& default_instance();
  
  void Swap(UnitySummonBossState_BossInfo* other);
  
  // implements Message ----------------------------------------------
  
  UnitySummonBossState_BossInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnitySummonBossState_BossInfo& from);
  void MergeFrom(const UnitySummonBossState_BossInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:game_connection.UnitySummonBossState.BossInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_time();
  inline void clear_has_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnitySummonBossState_2eproto();
  friend void protobuf_AssignDesc_UnitySummonBossState_2eproto();
  friend void protobuf_ShutdownFile_UnitySummonBossState_2eproto();
  
  void InitAsDefaultInstance();
  static UnitySummonBossState_BossInfo* default_instance_;
};
// -------------------------------------------------------------------

class UnitySummonBossState : public ::google::protobuf::Message {
 public:
  UnitySummonBossState();
  virtual ~UnitySummonBossState();
  
  UnitySummonBossState(const UnitySummonBossState& from);
  
  inline UnitySummonBossState& operator=(const UnitySummonBossState& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnitySummonBossState& default_instance();
  
  void Swap(UnitySummonBossState* other);
  
  // implements Message ----------------------------------------------
  
  UnitySummonBossState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnitySummonBossState& from);
  void MergeFrom(const UnitySummonBossState& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnitySummonBossState_BossInfo BossInfo;
  
  typedef UnitySummonBossState_traits traits;
  static const traits value = UnitySummonBossState_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnitySummonBossState_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnitySummonBossState_traits_traits_MIN;
  static const traits traits_MAX =
    UnitySummonBossState_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnitySummonBossState_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnitySummonBossState_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnitySummonBossState_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnitySummonBossState_traits_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // repeated .game_connection.UnitySummonBossState.BossInfo boss = 1;
  inline int boss_size() const;
  inline void clear_boss();
  static const int kBossFieldNumber = 1;
  inline const ::game_connection::UnitySummonBossState_BossInfo& boss(int index) const;
  inline ::game_connection::UnitySummonBossState_BossInfo* mutable_boss(int index);
  inline ::game_connection::UnitySummonBossState_BossInfo* add_boss();
  inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnitySummonBossState_BossInfo >&
      boss() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnitySummonBossState_BossInfo >*
      mutable_boss();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnitySummonBossState)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::game_connection::UnitySummonBossState_BossInfo > boss_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnitySummonBossState_2eproto();
  friend void protobuf_AssignDesc_UnitySummonBossState_2eproto();
  friend void protobuf_ShutdownFile_UnitySummonBossState_2eproto();
  
  void InitAsDefaultInstance();
  static UnitySummonBossState* default_instance_;
};
// ===================================================================


// ===================================================================

// UnitySummonBossState_BossInfo

// required int32 id = 1;
inline bool UnitySummonBossState_BossInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnitySummonBossState_BossInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnitySummonBossState_BossInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnitySummonBossState_BossInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 UnitySummonBossState_BossInfo::id() const {
  return id_;
}
inline void UnitySummonBossState_BossInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 time = 2;
inline bool UnitySummonBossState_BossInfo::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UnitySummonBossState_BossInfo::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UnitySummonBossState_BossInfo::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UnitySummonBossState_BossInfo::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 UnitySummonBossState_BossInfo::time() const {
  return time_;
}
inline void UnitySummonBossState_BossInfo::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// UnitySummonBossState

// repeated .game_connection.UnitySummonBossState.BossInfo boss = 1;
inline int UnitySummonBossState::boss_size() const {
  return boss_.size();
}
inline void UnitySummonBossState::clear_boss() {
  boss_.Clear();
}
inline const ::game_connection::UnitySummonBossState_BossInfo& UnitySummonBossState::boss(int index) const {
  return boss_.Get(index);
}
inline ::game_connection::UnitySummonBossState_BossInfo* UnitySummonBossState::mutable_boss(int index) {
  return boss_.Mutable(index);
}
inline ::game_connection::UnitySummonBossState_BossInfo* UnitySummonBossState::add_boss() {
  return boss_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_connection::UnitySummonBossState_BossInfo >&
UnitySummonBossState::boss() const {
  return boss_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_connection::UnitySummonBossState_BossInfo >*
UnitySummonBossState::mutable_boss() {
  return &boss_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnitySummonBossState_traits>() {
  return ::game_connection::UnitySummonBossState_traits_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnitySummonBossState_2eproto__INCLUDED
