// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnityCreateArmyGroup.proto

#ifndef PROTOBUF_UnityCreateArmyGroup_2eproto__INCLUDED
#define PROTOBUF_UnityCreateArmyGroup_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnityCreateArmyGroup_2eproto();
void protobuf_AssignDesc_UnityCreateArmyGroup_2eproto();
void protobuf_ShutdownFile_UnityCreateArmyGroup_2eproto();

class UnityCreateArmyGroup;

enum UnityCreateArmyGroup_traits {
  UnityCreateArmyGroup_traits_value = 4482
};
bool UnityCreateArmyGroup_traits_IsValid(int value);
const UnityCreateArmyGroup_traits UnityCreateArmyGroup_traits_traits_MIN = UnityCreateArmyGroup_traits_value;
const UnityCreateArmyGroup_traits UnityCreateArmyGroup_traits_traits_MAX = UnityCreateArmyGroup_traits_value;
const int UnityCreateArmyGroup_traits_traits_ARRAYSIZE = UnityCreateArmyGroup_traits_traits_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityCreateArmyGroup_traits_descriptor();
inline const ::std::string& UnityCreateArmyGroup_traits_Name(UnityCreateArmyGroup_traits value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityCreateArmyGroup_traits_descriptor(), value);
}
inline bool UnityCreateArmyGroup_traits_Parse(
    const ::std::string& name, UnityCreateArmyGroup_traits* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityCreateArmyGroup_traits>(
    UnityCreateArmyGroup_traits_descriptor(), name, value);
}
enum UnityCreateArmyGroup_Limit {
  UnityCreateArmyGroup_Limit_MaxNameSize = 28
};
bool UnityCreateArmyGroup_Limit_IsValid(int value);
const UnityCreateArmyGroup_Limit UnityCreateArmyGroup_Limit_Limit_MIN = UnityCreateArmyGroup_Limit_MaxNameSize;
const UnityCreateArmyGroup_Limit UnityCreateArmyGroup_Limit_Limit_MAX = UnityCreateArmyGroup_Limit_MaxNameSize;
const int UnityCreateArmyGroup_Limit_Limit_ARRAYSIZE = UnityCreateArmyGroup_Limit_Limit_MAX + 1;

const ::google::protobuf::EnumDescriptor* UnityCreateArmyGroup_Limit_descriptor();
inline const ::std::string& UnityCreateArmyGroup_Limit_Name(UnityCreateArmyGroup_Limit value) {
  return ::google::protobuf::internal::NameOfEnum(
    UnityCreateArmyGroup_Limit_descriptor(), value);
}
inline bool UnityCreateArmyGroup_Limit_Parse(
    const ::std::string& name, UnityCreateArmyGroup_Limit* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnityCreateArmyGroup_Limit>(
    UnityCreateArmyGroup_Limit_descriptor(), name, value);
}
// ===================================================================

class UnityCreateArmyGroup : public ::google::protobuf::Message {
 public:
  UnityCreateArmyGroup();
  virtual ~UnityCreateArmyGroup();
  
  UnityCreateArmyGroup(const UnityCreateArmyGroup& from);
  
  inline UnityCreateArmyGroup& operator=(const UnityCreateArmyGroup& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnityCreateArmyGroup& default_instance();
  
  void Swap(UnityCreateArmyGroup* other);
  
  // implements Message ----------------------------------------------
  
  UnityCreateArmyGroup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnityCreateArmyGroup& from);
  void MergeFrom(const UnityCreateArmyGroup& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UnityCreateArmyGroup_traits traits;
  static const traits value = UnityCreateArmyGroup_traits_value;
  static inline bool traits_IsValid(int value) {
    return UnityCreateArmyGroup_traits_IsValid(value);
  }
  static const traits traits_MIN =
    UnityCreateArmyGroup_traits_traits_MIN;
  static const traits traits_MAX =
    UnityCreateArmyGroup_traits_traits_MAX;
  static const int traits_ARRAYSIZE =
    UnityCreateArmyGroup_traits_traits_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  traits_descriptor() {
    return UnityCreateArmyGroup_traits_descriptor();
  }
  static inline const ::std::string& traits_Name(traits value) {
    return UnityCreateArmyGroup_traits_Name(value);
  }
  static inline bool traits_Parse(const ::std::string& name,
      traits* value) {
    return UnityCreateArmyGroup_traits_Parse(name, value);
  }
  
  typedef UnityCreateArmyGroup_Limit Limit;
  static const Limit MaxNameSize = UnityCreateArmyGroup_Limit_MaxNameSize;
  static inline bool Limit_IsValid(int value) {
    return UnityCreateArmyGroup_Limit_IsValid(value);
  }
  static const Limit Limit_MIN =
    UnityCreateArmyGroup_Limit_Limit_MIN;
  static const Limit Limit_MAX =
    UnityCreateArmyGroup_Limit_Limit_MAX;
  static const int Limit_ARRAYSIZE =
    UnityCreateArmyGroup_Limit_Limit_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Limit_descriptor() {
    return UnityCreateArmyGroup_Limit_descriptor();
  }
  static inline const ::std::string& Limit_Name(Limit value) {
    return UnityCreateArmyGroup_Limit_Name(value);
  }
  static inline bool Limit_Parse(const ::std::string& name,
      Limit* value) {
    return UnityCreateArmyGroup_Limit_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required bytes name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // @@protoc_insertion_point(class_scope:game_connection.UnityCreateArmyGroup)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_UnityCreateArmyGroup_2eproto();
  friend void protobuf_AssignDesc_UnityCreateArmyGroup_2eproto();
  friend void protobuf_ShutdownFile_UnityCreateArmyGroup_2eproto();
  
  void InitAsDefaultInstance();
  static UnityCreateArmyGroup* default_instance_;
};
// ===================================================================


// ===================================================================

// UnityCreateArmyGroup

// required bytes name = 1;
inline bool UnityCreateArmyGroup::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnityCreateArmyGroup::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnityCreateArmyGroup::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnityCreateArmyGroup::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& UnityCreateArmyGroup::name() const {
  return *name_;
}
inline void UnityCreateArmyGroup::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void UnityCreateArmyGroup::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void UnityCreateArmyGroup::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UnityCreateArmyGroup::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* UnityCreateArmyGroup::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_connection

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityCreateArmyGroup_traits>() {
  return ::game_connection::UnityCreateArmyGroup_traits_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_connection::UnityCreateArmyGroup_Limit>() {
  return ::game_connection::UnityCreateArmyGroup_Limit_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnityCreateArmyGroup_2eproto__INCLUDED
